### ISSUE TITLE
Asking for support to ".gql" format

### ISSUE THREAD

**Issue by e200** [gql-dart/ferry#107]
".gql"  is short and also a valid graphql schema format.

Can the generator recognize this extension too?

**Comment by smkhalsa** [comment]
No, .gql won't work. We aren't using an external JS library to parse the graphql files.

**Comment by e200** [comment]
Why did you close this issue?
I know you aren't useing a JS library to parse the files, makes no sense.

**.gql** and **.graphql** have the same content, so what's the problem?

**Comment by e200** [comment]
I know you aren't using a JS library to parse the files, makes no sense.

.gql and .graphql have the same content, so what's the problem parsing it?

**Comment by smkhalsa** [comment]
The file extensions are not part of the official spec, but `.graphql` [seems to be the canonical choice](https://github.com/graphql/graphql-spec/issues/203#issuecomment-513525810).

I know some libraries like `graphql-tools`(js) support `.gql` files. However, I think it's probably better to stick with just `.graphql` until there is more consensus around `.gql` or other extensions being supported.
