### ISSUE TITLE
New typed links architecture not backward compatible

### ISSUE THREAD

**Issue by iscriptology** [gql-dart/ferry#108]
Please make such refactors backward compatible as it makes it super hard to update. (no responseStream method?)
In general a library such as this that is so central to every app using it must keep the number of breaking changes to a minimum.

**Comment by smkhalsa** [comment]
I'm not sure what the suggestion is here. Moving to a Link-based API necessitated a couple of breaking changes, but we followed the appropriate semver version bump for breaking changes. 

This is pre v1 software, so breaking changes are to be expected.

That said, I'm pretty satisfied with the API, so hopefully we won't have many more breaking changes before v1.
