### ISSUE TITLE
Not able to correctly generate the code

### ISSUE THREAD

**Issue by QAQyzk** [gql-dart/ferry#109]
output after run `pub run build_runner build --delete-conflicting-outputs` 
```
[INFO] Generating build script completed, took 483ms
[WARNING] Configuring `gql_build:serializer_builder` in target `app:app` but this is not a known Builder
[INFO] Reading cached asset graph completed, took 73ms
[INFO] Checking for updates since last build completed, took 1.0s
[INFO] Running build completed, took 23ms
[INFO] Caching finalized dependency graph completed, took 79ms
[INFO] Succeeded after 115ms with 0 outputs (0 actions)
```
error in the generated file `test.req.gql.dart`
`Target of URI doesn't exist: 'package:app/gql/query/test.op.gql.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist`

Any solutions? 

Thanks

**Comment by smkhalsa** [comment]
Do you have gql_build as a dependency I'm your pubspec.yaml?

**Comment by QAQyzk** [comment]
@smkhalsa 
Thanks for help!
I just realized that I'm using `pub run` in a flutter project, after I changed to use `flutter pub run` it works perfectly now.
