### ISSUE TITLE
Consider not providing a requestId by default

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/ferry#110]
If a user instantiates a request within the build method of a Flutter widget and doesn't manually provide a `requestId`, ferry will automatically assign a `uuid`.

This is problematic because it will cause ferry to re-execute the request every time the widget is built.

We should consider removing the default `uuid` assignment in ferry_generator.

**Comment by smkhalsa** [comment]
For now, I added a note in the docs about providing a requestId if the operation is instantiated in the Widget build method to prevent re-execution.

**Comment by jifalops** [comment]
imo the default request ID would hash the query and variables together so if the same exact request is sent it will have the same generated query ID.

**Comment by danielmahon** [comment]
@smkhalsa I just ran into this being a tad confusing for "refetching", in the docs it says to just add a new event to the stream controller but if you don't manually assign a `requestId` then the refetch will fail if you are triggering it inside a TypedLink... like a retry link

**Comment by smkhalsa** [comment]
@jifalops default request IDs have been completely removed. Are you suggesting adding them back? If so, why?

**Comment by smkhalsa** [comment]
@danielmahon is this a documentation issue? Or is there any improvement that can be made here to the client itself?
