### ISSUE TITLE
NoSuchMethodError: invalid member on null: 'loading'

### ISSUE THREAD

**Issue by garyrutland** [gql-dart/ferry#114]
Hi,

Been using the library few a weeks now but hit a problem and not sure how to debug it.

Using the `Operation` widget and using a similar setup to the example I have started getting the response `NoSuchMethodError: invalid member on null: 'loading'` but can't find a way to debug it.

My code looks something similar to this:
```
final GMyReq myRequest = GMyReq((b) => b
      ..fetchPolicy = FetchPolicy.NetworkOnly
      ..vars.uuid = widget.uuid);

return Operation(
  operationRequest: festivalRequest,
  client: _client,
  builder: (BuildContext context, OperationResponse<GMyData, GMyVars> response) {
    print('RESPONSE');
    print(response);
    print('RESPONSE END');

    if (response.loading)
      return Center(child: CircularProgressIndicator());

    // ...
  }
);
);
```

But the `print` command outputs the following:
```
RESPONSE
Instance of 'OperationResponse<GMyData, GMyVars>'
RESPONSE END
RESPONSE
null
RESPONSE END
```

Is there a way for me to find out why null is being returned?
I've added `gql_error_link` and a `ErrorLink` to my client but it doesn't seem to be getting triggered.

Thanks,
Gary

**Comment by garyrutland** [comment]
I was able to update the client so I could print out the response using the `TransformLink` and compared the response of a failing response to a successful response from the same request and the only difference between the two is when I was using a `Date` scalar.

When a value was returned (i.e. 2020-11-07) everything worked fine, but if `null` was returned I got the above issue.

To clarify, the schema is declared as `Date` and not `Date!`.
Is it possible this is a bug?

I might be able to get around the issue by implementing a custom scalar based on the docs.

**Comment by garyrutland** [comment]
So after adding a custom serialiser, while it has made life a bit easier for non-null values any response that has a `null` response doesn't even get to the serialiser.

**Comment by smkhalsa** [comment]
What version of ferry are you using?

Are any exceptions being thrown (including any that are being caught by your ErrorLink?)

**Comment by garyrutland** [comment]
From my `pubspec.yaml` file:

```
  ferry: ^0.8.0
  ferry_flutter: ^0.3.0
  gql_http_link: ^0.3.2
  gql_error_link: ^0.1.1-alpha
  gql_transform_link: ^0.1.5
```

I've implemented both `onException` and `onGraphQLError` with the following very simple functions, please do tell me if I've done something wrong but nothing ever got printed from them.

```
ErrorLink(
  onException: handleException,
  onGraphQLError: handleGraphQlError,
)

Stream<Response> handleException(Request request, NextLink forward, LinkException exception) async* {
  print('handleException');
  print(exception);
  print('handleException END');

  yield* forward(request);

  throw exception;
}

Stream<Response> handleGraphQlError(Request request, NextLink forward, Response response) async* {
  print('handleGraphQlError');
  print(response);
  print('handleGraphQlError END');

  yield* forward(request);

  return;
}
```

This is what I do get though:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown building
StreamBuilder<OperationResponse<GMyData, GMyVars>>(dirty, state:
_StreamBuilderBaseState<OperationResponse<GMyData, GMyVars>,
AsyncSnapshot<OperationResponse<GMyData, GMyVars>>>#259b7):
NoSuchMethodError: invalid member on null: 'loading'
```

Hopefully this helps?

**Comment by garyrutland** [comment]
I'm not sure what I've done now, but every time I use `Operation` it's coming back with that error now.
I can see valid responses coming back from the server though in the `TransformLink` through `responseTransformer`.

Again, this is incredibly basic:
```
Response transformResponse(Response response) {
  print('TRANSFORM RESPONSE');
  print(response);
  print('TRANSFORM RESPONSE END');

  return response;
}
```

I'm at a bit of a loose end now and now sure how to debug this, I'm fairly sure it's something I've done but have no idea what.

**Comment by smkhalsa** [comment]
It sounds like there could be an exception within the TypedLink chain, but It's very difficult to provide any insight without seeing your specific setup.

Can you provide a basic repro?

**Comment by garyrutland** [comment]
I will try and set something up but it seems to be when returning `null` for a custom `Date` scalar, whether you define a custom serialiser or not.

**Comment by garyrutland** [comment]
Been trying to put together a new slim api and app but having difficulties getting it to work.
Following the instructions [here](https://ferrygraphql.com/docs/setup) I've updated `pubspec.yaml` with the following:

```
dependencies:
  ferry: ^0.8.0
  gql_http_link: ^0.3.2

dev_dependencies:
  ferry_generator: ^0.3.0
  build_runner: ^1.10.4
```

Then when running `flutter pub get` I get the following:

```
Because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer ^0.40.1, build_runner >=1.10.3 requires analyzer ^0.40.1.
And because ferry_generator >=0.2.1 depends on gql_code_builder ^0.1.2 which depends on analyzer ^0.39.14, build_runner >=1.10.3 is incompatible with ferry_generator >=0.2.1.
So, because app depends on both ferry_generator ^0.3.0 and build_runner ^1.10.4, version solving failed.
Running "flutter pub get" in app...
pub get failed (1; So, because app depends on both ferry_generator ^0.3.0 and build_runner ^1.10.4, version solving failed.)
```

**Comment by smkhalsa** [comment]
Please fix your build_runner version to 1.10.1 for now.

**Comment by garyrutland** [comment]
Ok, I've got a repo with what seems to be simplest thing possible but it doesn't seem like responses are coming back at all.
It may be due to what I'm using to mock the API but if it is, I'm not sure how.

https://github.com/garyrutland/flutter-ferry-date-example

**Comment by garyrutland** [comment]
Apologies, it's Sunday and my brain wasn't working properly.
Reason there was no responses from the API was because I forgot about CORS.

I've now got the example to work and printed out the response in the `TransformLink` response and in the `OperationResponse` response.

```
# TransformLink
Response(data: {__typename: Query, items: [{__typename: Item, id: 4eb43f2a-c757-4691-a8f2-9b2132e6c687, date: 2020-11-08}, {__typename: Item, id: 8ae4c0a9-8484-487d-b1ec-405a3f7e8b33, date: null}]}, errors: null, context: Context({ResponseExtensions: Instance of
'ResponseExtensions', HttpLinkResponseContext: Instance of 'HttpLinkResponseContext'}))
```

```
# OperationResponse
GItemsData {
  G__typename=Query,
  items=[GItemsData_items {
    G__typename=Item,
    id=4eb43f2a-c757-4691-a8f2-9b2132e6c687,
    date=GDate {
      value=2020-11-08,
    },
  }, GItemsData_items {
    G__typename=Item,
    id=8ae4c0a9-8484-487d-b1ec-405a3f7e8b33,
  }],
}
```

I've locked the versions to the same as what is in the lock file for my main project but it's all working.

My main project is printing out the similar results in `TransformLink` (i.e. `Date` does return `null` in the same way).
Is there any way for me to inject in between these the two above to debug?

**Comment by garyrutland** [comment]
...face palm moment...

So apparently my API had it marked as `Date` but for some reason the schema I had in my app had it set to `Date!`.
I've now removed the `!` and it's all working again.

Is there anyway of putting in a slightly more useful error/exception for idiots like me?

**Comment by garyrutland** [comment]
Been looking into this further and the `Date` might have been a red herring.
I also have a `DateTime` scalar which always returns in ISO8601 format (i.e. 2020-11-08T18:00:00+0000) and never null.

Whenever I query these I can see them in the response in `TransformLink` but then get the error in `OperationResponse` and once removed from the query it all works again.
The response from the API is valid and I have hard coded it in my example, but that example seems to work fine.

It's starting to get quite infuriating that there is some magic going on (to me at least) between the response from the API and the `OperationResponse` being called that I can't seem to debug.

**Comment by smkhalsa** [comment]
I just ran your example, and I'm not able to reproduce the Exception. The request is executing correctly for me.

The ferry client itself is just a chain of [TypedLinks](https://ferrygraphql.com/docs/customization). It might be helpful to download the ferry repo locally and set a dependency_override in your project to point to the local version so you can set breakpoints within the ferry code.

**Comment by garyrutland** [comment]
So I've just run `flutter pub run build_runner clean` removed all related packages from `pubspec.yaml`, uninstalled and re-installed and everything now seems to be working.

🤷‍♂️

**Comment by garyrutland** [comment]
Ah, I've finally replicated it, looks like it's when setting `type_overrides` and specifically for `DateTime`.
If you pull and try my example repo you should now get the loading error.

```
type_overrides:
  DateTime:
    name: DateTime
```

**Comment by garyrutland** [comment]
Have you been able to replicate this now?

**Comment by smkhalsa** [comment]
It looks like you forgot to include a [custom serializer](https://ferrygraphql.com/docs/custom-scalars#configure-custom-serializer) for DateTime. Ferry only knows how to serialize Dart Data Types out of the box and has no way of knowing how to parse your date string into a Dart DateTIme object.

**Comment by garyrutland** [comment]
Sorry it's taken a while to look back into this, had other things on.

I had originally added custom serialisers for all three scenarios (DateTime, Date & Time) which still resulted in the error.
When trying to replicate on my test repo above I only created the serialiser for DateTime which worked without issue.
I think I then remembered reading somewhere that Date & Time didn't actually need a custom serialiser so removed them leaving just the DateTime serialiser and everything then seemed to start working.

I can try and update my test repo to see if that causes the issue as well but not sure if there's a simple explanation instead?

**Comment by garyrutland** [comment]
So this continues, if I have one serialiser for `DateTime` but also state that a custom scalar for `Time` should be overridden to `DateTime` it would appear that the custom serialiser picks it up too and then errors as it can't parse it.
If I add a second custom serialiser for `Time` the whole thing errors again.

I have updated my example in https://github.com/garyrutland/flutter-ferry-date-example to replicate this.

Would appreciate you taking a look to see what is either wrong on my part or if there is a bug.

Thanks.

**Comment by smkhalsa** [comment]
@garyrutland I don't think I'll have time to dig into this again within the next week or two.

**Comment by smkhalsa** [comment]
@garyrutland were you able to figure this out?

**Comment by smkhalsa** [comment]
closing this since I haven't heard back, but feel free to reopen if this is still an issue.
