### ISSUE TITLE
Pass Response "extensions" data through to OperationResponse

### ISSUE THREAD

**Issue by shamnex** [gql-dart/ferry#117]
Thank you so much for the wonderful package and I've certainly enjoyed working with it.

I recently hopped on a project and the  GraphQL server returns some meta data not part of the original data and it looks like something like this.
```
{
  "success": true,
  "message": "graphql query executed successfully",
  "data": {
    "getArticles": [
      {
        "_id": "5f44f9db4e0de350f0f3c561",
        "status": "online",
        "reactions": 0,
        "comments": 0,
        "bookmarked": false,
      }
    ]
  },
  "meta": {
    "totalPage": 46045,
    "perPage": 1,
    "currentPage": 1,
    "totalDocument": 46045
  }
}
```
I need to have access to the MetaData and I can't seem to figure out a way of adding it to the `OperationResponse` without making a lot of changes to the core Library itself. Is there a way to have access to the original json format?

Thanks a lot in advance.

**Comment by smkhalsa** [comment]
According to the GraphQL [spec](https://spec.graphql.org/June2018/#sec-Response-Format), the response should only contain the following keys:

1. `data`
2. `errors`
3. `extensions`

So it doesn't seem like your server response is GraphQL spec compliant.

We could add an `extensions` field on the `OperationResponse` that could allow for arbitrary data, and you could adjust your server to route the metadata through the extensions field.

If you're not able to edit your server response, without editing the `ferry` internals, you'd probably need to add a `Link` to capture and store the metadata manually.

**Comment by smkhalsa** [comment]
To add to my answer above, if we add an `extensions` key to the `OperationResponse`, you should be able to add a `Link` to your chain that simply maps your metadata to the extensions field.

So your updated response would look like this:

```


{
  "data": {
    "getArticles": [
      {
        "_id": "5f44f9db4e0de350f0f3c561",
        "status": "online",
        "reactions": 0,
        "comments": 0,
        "bookmarked": false,
      }
    ]
  },
  "extensions: {
    "success": true,
    "message": "graphql query executed successfully",
    "meta": {
      "totalPage": 46045,
      "perPage": 1,
      "currentPage": 1,
      "totalDocument": 46045
    }
  }
}
```

**Comment by shamnex** [comment]
Thanks a lot for the prompt response. I believe adding the `extensions` field to the `OperationResponse` would be much needed. Would be waiting for the update.  Thanks a lot for the hard work.

**Comment by smkhalsa** [comment]
Do you need the extensions data to be cached? Or would it be enough to just receive it back in the response for the operation?

**Comment by shamnex** [comment]
Cached preferably. It would be enough just to receive it back in the operation as I'm not using any sort of caching in this application but I reckon someone might need it down the line. 

Thanks again for all the good work.

**Comment by tiennguyen9988** [comment]
The present with latest version (^0.10.4), I still can't access to extensions data from response. Please give me any guide for resolve this issue.
Thanks!

**Comment by smkhalsa** [comment]
This hasn't been implemented yet. Pars welcome

**Comment by tiennguyen9988** [comment]
I hope this feature will be implemented soon, i really need it for my project.
Thanks!
