### ISSUE TITLE
[normalize] Only the first of multiple queries with a common ancestor field can be read from cache

### ISSUE THREAD

**Issue by jl-mindius** [gql-dart/ferry#132]
Using graphql-flutter but it seems to be normalize related. Using an example, we have a situation where only the item query result can be read from cache.

```graphql
query UserItems {
  user { # UserType
    id # u12
    items {
      edges {
        node { # ItemType
          id # i34
          title
        }
      }
    }
  }
}

query UserSettings {
  user { # UserType
    id # u12
    settings { # SettingsType
      id # s56
      theme
    }
  }
}
```

When listing keys we get:

```json
[
  "ItemType:i34",
  "...several items..."
  "Query",
  "SettingsType:s56",
  "UserType:u12",
]
```

Then getting the data for those keys:

```json
"ItemType:i34": {
  "id": "i34",
  "title": "The title",
}
"...several items..."

"Query": {
  "user": {
    "$ref": "UserType:u12",
    "settings": {
      "$ref": "SettingsType:s56",
    },
  },
}

"SettingsType:s56": {
  "id": "s56",
  "theme": "dark",
}

"UserType:u12": {
  "id": "u12",
  "items": {
    "edges": [
      { "node": { "$ref": "ItemType:i34" } },
      "...several items..."
    ],
  },
}
```

The items are always fetched first since that query runs when the app starts. I've tried to step through `denormalizeNode` when the settings query is read from cache and have gotten to a point where it's at Query.user. Seeing the `$ref`, it reads `UserType:u12` which then doesn't contain the `settings` key, causing a null result (because of partial data?).

To get around this can probably just change the schema to remove the common `user` ancestor, but it would be nice if this approach also worked.

**Comment by smkhalsa** [comment]
Your normalized data `Query` => `user` doesn't look right.

```
"Query": {
  "user": {
    "$ref": "UserType:u12",
    "settings": {
      "$ref": "SettingsType:s56",
    },
  },
}
```

There shouldn't be both a reference and child fields. If a reference is present, `normalize` searches for fields on the normalized object that is referenced.

Are you using a custom `FieldPolicy.merge()` method?

**Comment by jl-mindius** [comment]
Nothing custom, just the regular `Query` widget from graphql-flutter. So it's possibly the cache writing/`normalize` part that's the actual problem? Is there something from that part I can provide examples of?

**Comment by smkhalsa** [comment]
To pinpoint the issue (and clarify whether it is indeed an issue with `normalize`), it'd be helpful if you could add a failing test using your query and response data to check how normalize is normalizing the data.

**Comment by jl-mindius** [comment]
Sure, I'll see what I can do.

**Comment by jl-mindius** [comment]
So I made a test based on the example above and it passed, causing me to investigate the real data in more detail. Turns out I'm blind and the example didn't match exactly after all — the settings query was missing `id` for the user so it couldn't be fully normalized. Thanks for the help!
