### ISSUE TITLE
REST support

### ISSUE THREAD

**Issue by chimon2000** [gql-dart/ferry#133]
Apollo has a unique feature where it allows you to use the library to communicate with [REST APIs](https://www.apollographql.com/docs/link/links/rest/) as well as GraphQL.  

This feature is extremely useful for applications that have legacy APIs.  In our case, we keep a thin repository layer around just for the sake of merging GraphQL requests with our State Management layer, and this would eliminate a lot of code.  

I am hoping you'll consider adding it to ferry.

**Comment by smkhalsa** [comment]
@chimon2000 this seems like a bit of a corner case, so I don't think it belongs in the Ferry core. 

However, `ferry`'s architecture is highly [extensible](https://ferrygraphql.com/docs/customization). You should be able to implement something yourself by adding a custom TypedLink.

**Comment by chimon2000** [comment]
I love this idea and that's exactly how it was implemented in Apollo (as an Apollo Link separate from core)

**Comment by smkhalsa** [comment]
Closing this since it's out of scope.
