### ISSUE TITLE
How do I test the ferry implementation?

### ISSUE THREAD

**Issue by Yeikel200** [gql-dart/ferry#136]
I see that it is very easy to implement ferry, however I do not see a way to test the implementation. What happens if radical changes are suddenly made in the API? You have to completely restructure the project !!

**Comment by smkhalsa** [comment]
@Yeikel200 I'm not sure what your question is

**Comment by Yeikel200** [comment]
What is the best way to test the ferry implementation?

**Comment by smkhalsa** [comment]
Are you speaking about testing ferry's internal code? There are a number of tests through the various packages.

Or are you asking about testing an app that uses ferry?

**Comment by Yeikel200** [comment]
> Or are you asking about testing an app that uses ferry?

Yes, test an app that implements ferry !!

**Comment by Yeikel200** [comment]
> Or are you asking about testing an app that uses ferry?

Yes, test an app that implements ferry !!

**Comment by smkhalsa** [comment]
The ferry client's request method returns a dart Stream. You can test it as you would any other stream.

I suggest taking a look at Flutter's testing documentation.

I'm closing this since it's not related to ferry itself.
