### ISSUE TITLE
Wondering if there are plans for Ferry to support Graphql schema stitching in the future? 

### ISSUE THREAD

**Issue by haydenfoote** [gql-dart/ferry#140]

**Comment by smkhalsa** [comment]
Schema stitching is a feature on the GraphQL server, not the client. What issue exactly are you seeing in Ferry preventing you from using stitching on your server?

**Comment by haydenfoote** [comment]
> Schema stitching is a feature on the GraphQL server, not the client. What issue exactly are you seeing in Ferry preventing you from using stitching on your server?

Many thanks for your reply!  Yes, hoping to pull data from multiple GraphQL endpoints ... both MongoDB Realm but different end points ...

**Comment by smkhalsa** [comment]
Sounds like you probably would want to set up a gateway service to sit between your client and databases. Alternatively, you could create a custom `gql_link` that decides which backend to send the request to.

I'm closing this issue, since it isn't related to Ferry.

**Comment by haydenfoote** [comment]
> Sounds like you probably would want to set up a gateway service to sit between your client and databases. Alternatively, you could create a custom `gql_link` that decides which backend to send the request to.
> 
> I'm closing this issue, since it isn't related to Ferry.

Great, many thanks for the advice!
