### ISSUE TITLE
Offline mutations cannot be retried on app restart/on another screen

### ISSUE THREAD

**Issue by akinsho** [gql-dart/ferry#142]
Apologies for more issues relating to #137. Essentially I realised that my previous issue wasn't clear enough to explain what I was seeing and although I did make progress by adding a `requestId` I now have a better idea of another reason why I'm not (occasionally) seeing my offline requests being executed.

#### Background
So my use case is allowing a user to complete a flow offline `1. check in` -> `2. add notes` -> `3. check out`.
All three mutations need to be persisted whilst offline and *re-executed at a later date* e.g. if a user closes the app and restarts it or has since moved on to other screen within the app.

#### Problem
I've observed that the example offline link (which I appreciate is just an example) works via adding requests to the request controller's stream. Currently this works with the default request controller link by checking for a request id that matches that of the request added to the stream. So if I have hit a button to carry out step 1 but I was offline then when next I come online on that same page, then that mutation is successfully carried out.

The issue for me comes if step 1-3 were carried out and the app restarts in the interim, the requests can't be completed because they will always fail the following check in the request controller.
```dart
        .whereType<OperationRequest<TData, TVars>>()
        .where(
          (req) => req.requestId == null
              ? req == request
              : req.requestId == request.requestId,
        )
```
NOTE: This also seems to be the case when moving between screens, if the previous screen's subscription has been closed then a subsequently rehydrated request also never gets called.

What I'm hoping for is some advice of how to do this with what `ferry` provides i.e. how can I re-implement `requestController` so that if it has never seen a request before it just executes it anyway? I've tried using `client.request` on app restart using the rehydrated queries but the `client.request` call expects a `TData,TVars` type argument which aren't available when deserialising the mutation e.g.

```dart
      final req = serializers.deserialize(json) as OperationRequest; // I don't have access to TData,TVars here
      // Run unexecuted mutations
      client.request<dynamic, dynamic>(req);
```

so this then fails the type check in the `requestController`. Is there some way to retrieve `TData,TVars` from during deserialisation that you might be aware of? Or alternatively how can I retry my offline queries without the presumption of a previous request or existing open stream?

**Comment by smkhalsa** [comment]
Ah yes, this is a significant problem with the example offline link.

Simply adding an operation to the requestController Sink doesn't cause it to be executed. It's listening to the response stream for a given request that actually pulls that request through the TypedLink chain, causing it to be executed.

The easiest way to address this would probably be to have the offline link actually listen to a responseStream for the given request as opposed to simply adding the request to the requestController. For example, we could update `_handleOnConnect()` to something like:

```dart
  void _handleOnConnect() => mutationQueueBox.values.forEach((json) async {
        final OperationRequest req = serializers.deserialize(json);

        // Run unexecuted mutations
        await client.request(req).firstWhere((res) => res.dataSource == DataSource.Link);
      });
```
Of course, we'd have to pass our client in as a dependency.

---

As a side note regarding the code you referenced above, the serializer should deserialize into the correct full type (including TData & TVars) at runtime.

In your code above, since you are casting to `OperationRequest` without any type arguments, Dart casts this to `OperationRequest<dynamic, dynamic>`. You probably just want to do this...

```dart
final req = serializers.deserialize(json);
client.request(req);
```

If you want to add compile-time type arguments, the TData & TVars classes are generated in the `my_query.data.gql.dart` and `my_query.var.gql.dart` files.

**Comment by akinsho** [comment]
@smkhalsa thanks that's very helpful. I had started to try by passing a callback to on connect and then using the types of each query to resolve the type issues e.g.
```dart
void _handleOnConnect(void Function(OperationRequest) callback) {
  final OperationRequest req = serializers.deserialize(json);
  callback(req)
}
// Different point elsewhere where the callback is defined
void myCallback(OperationRequest req) {
  if (value is GmyRequest) {
    client.request(req).listen(handle) // <-- at this point the types can be inferred.
  }
}
```
That actually works but is very manual and was more of a test that a `client.request` with the right type information would be the solution which your answer also confirms. 

```dart
 await client.request(req).firstWhere((res) => res.dataSource == DataSource.Link)
```
just so I'm clear the line above you suggested in this case would mean waiting for each request that had come from a link, I'm assuming that since the client request is called inside the offline link that requests made from here will have their source set to `DataSource.Link`. Is waiting for this here primarily to ensure sequencing? since otherwise you could just call `.request`.

Lastly regarding the compile time type arguments inside of my project the value of `req` in
```dart
final req = serializers.deserialize(json); <-- req is Object
```
is an `Object` which is what the deserialize function returns, I believe that `built_value` has some other function for getting the specific type information back but you have to know the types at the point of usage e.g. `serializeWith<MyArg>` is how I believe that works.

**Comment by smkhalsa** [comment]
The firstWhere in my code above is is filtering the stream of responses to only include the first response received from a link. Otherwise, if for some reason you have a cached mutation, you would get a cached response.

With respect to the type args, the filter on request controller are based on runtime types, and the serializer will deserialize to the correct type at runtime, so you shouldn't have to do any type casting to ensure the specific type at compile time.

**Comment by akinsho** [comment]
Thanks for the explanation @smkhalsa, will give this a try 🙏🏿 .

Regarding the type casting I was primarily doing that since my project uses `strong-mode` so `implicit-casting` isn't allowed, I've just disabled it for the link so I can move on. Re. the type arguments in generated files, I'm aware of those, the issue in this context was that I don't just need one matching set but essentially the equivalent of `TData,TVars` which isn't possible to pass down at that point. Anyway it's disabled for now.

**Comment by smkhalsa** [comment]
> Regarding the type casting I was primarily doing that since my project uses strong-mode so implicit-casting isn't allowed, I've just disabled it for the link so I can move on. Re. the type arguments in generated files, I'm aware of those, the issue in this context was that I don't just need one matching set but essentially the equivalent of TData,TVars which isn't possible to pass down at that point. Anyway it's disabled for now.

This should work and will retain the type arguments at runtime:

```dart
final OperationRequest req = serializers.deserialize(json);
```

But this is specifically casting to `OperationRequest<dynamic, dynamic>`

```dart
final req = serializers.deserialize(json) as OperationRequest;
```

**Comment by akinsho** [comment]
Managed to get it working. I just tried using 
```dart
final OperationRequest req = serializers.deserialize(json);
```
This actually leads to the same issue,]tjkjk as `dynamic` is implicit. I did manage to get it to work using
```dart
final req =  serializers.deserialize(json) as OperationRequest<Object, Object>;
// lower down
      await client
          .request<Object, Object>(req)
```
So there's a subtlety to dart's type system here since as far as I knew they would equate to essentially the same thing, could also just be something about `whereType` works 🤷🏿‍♂️ 🧐

**Comment by akinsho** [comment]
Alright I believe I've managed to get this working with your help @smkhalsa thanks again 🙌🏿 . I'm hoping once I've gotten some tests for it and added in some backoff + retry logic I could contribute it back as another offline link? or just an example up to you (/my schedule at work 😓)

**Comment by smkhalsa** [comment]
@akinsho great! Yes, please do submit a PR.

Are your changes simply improvements / fixes to the existing offline link? Or do you think it belongs in its own link?

**Comment by akinsho** [comment]
@smkhalsa so far they are mainly fixes, but 2 things I'm working on as they are necessary for my project are
* Enforced sequential ordering, not sure if this is a must have for everyone but it is for me
* A backoff and retry mechanism, I want to be able to say try `x` times then run `callback` which can be logging or whatever else

To me the above are essential but don't know if that might be too much or undesirable to bundle with the original link, the second would be opt in, the first would not. Would you prefer it as changes to the original or move one or both of those bits of functionality to a new link?

**Comment by smkhalsa** [comment]
@akinsho I imagine both of those are common requirements for an offline link. If we can allow for opting out, I think it'd be great to include them.

I suggest that we create a `ferry_offline_client` package as a plug & play offline solution that composes together an offline-ready TypedLink, including this offline mutation link with sensible defaults (e.g. sequential ordering) and a Hive Store. 

Users could simply do something like:

```dart
import 'package:gql_http_link/gql_http_link.dart';
import 'package:ferry_offline_client/ferry_offline_client.dart';

Future<OfflineClient> initClient() async {
  final link = HttpLink("[path/to/endpoint]");
  return await OfflineClient.init(link: link); 
}
```

This would initialize the `hive` boxes and return a ready-to-use offline link.
