### ISSUE TITLE
Add Cookies to every request

### ISSUE THREAD

**Issue by V3lop5** [gql-dart/ferry#145]
Hello,
I'm planning to use ferry as GraphQL client in for an api protected with session cookies.
How can I intercept the requests and provide the required cookies?

Currently I'm using the simple http dependency in my flutter project for REST requests against my webserver. 
Is there any way that ferry uses the same http client for the requests against the graphql endpoint?

It would be nice, if you can help me out!

**Comment by smkhalsa** [comment]
You'll do this using a gql_link. Take a look at the examples in that package.

**Comment by V3lop5** [comment]
Thanks alot.

In case anyone else wonders gql_http_link's HttpLink can take a HttpClient as [parameter](https://github.com/gql-dart/gql/blob/402d40573031b2206128a8d4e384f96fef46f55a/links/gql_http_link/lib/src/link.dart#L104). I found no example showing this feature.

```dart
import 'package:http/browser_client.dart';
import 'package:http/http.dart' as http;
import 'package:ferry/ferry.dart';
import 'package:gql_http_link/gql_http_link.dart';

final httpClient = http.Client(); // use this for REST requests

if (httpClient is BrowserClient) 
   (httpClient as BrowserClient).withCredentials = true; // Allow usage of cookies

final httpLink = HttpLink("http://localhost:8080/graphql", httpClient: httpClient);

final gqlClient = Client(link: httpLink); // use this for GraphQL requests
```

Now all my REST and GraphQL requests sharing the same cookies.
