### ISSUE TITLE
Proper use of FieldPolicy.read?

### ISSUE THREAD

**Issue by seanconnollydev** [gql-dart/ferry#153]
I have 2 queries run sequentially where I expect the 2nd query to be able to retrieve its results from the normalized cache.

First query:
```graphql
aliases(id: "alias_id") {
  data {
    id
    community { # <-- This of type Community
      id
      name
    }
  }
}
```

Second query:
```graphql
community (id: "community_id") { # <-- Also of type Community
  id
  name
}
```

The second query will result in another network request, I believe because it is a different query and the normalized cache logic doesn't assume that it can use the cached `Community` result (though I don't 100% understand why this is the default behavior).

I have solved a similar problem in the past with Apollo using [Field policy read](https://www.apollographql.com/docs/react/caching/advanced-topics/#cache-redirects-using-field-policy-read-functions).

I noticed Ferry also has `TypePolicy` and `FieldPolicy`, though the docs are a bit thin on how to use these.

This is what I ended up with, and it works but I'm not sure if this is the correct way to configure the `FieldPolicy` for my use case.

```dart
Client(
        link: ...
        cache: Cache(
          typePolicies: {
            'Query': TypePolicy(
              queryType: true,
              fields: {
                'community': FieldPolicy(
                  keyArgs: ['id'], // <--- Omitting this results in an error in `field_key.dart`
                  read: (existing, options) {
                    final toRef = options.toReference({
                      '__typename': 'Community',
                      'id': options.args['id'],
                    });

                    return options.readField(options.field, toRef);
                  },
                )
              },
            )
          },
        ),
      ),
```

Does this look right? Is there a reason it isn't documented?

**Comment by smkhalsa** [comment]
@seanconnollydev Yes, what you are trying to do is probably one of the more common use cases for `FieldPolicy.read()`, and your usage looks correct to me.

One thing to keep in mind though is that using this approach `ferry` will only ever resolve community(id: ...) from the cache, so the only way for that data to be populated is for another query to return the data. In other words, you can't every actually make a network request for that data directly.

I simply haven't gotten around to documenting `FieldPolicy`s. The functionality is equivalent to Apollo, so I've directed people to read the Apollo docs in the past to understand how they work. If you want to help out, feel free to open a PR on the [docs](https://github.com/gql-dart/ferry-docs) repo.
