### ISSUE TITLE
[normalize] Null Safety

### ISSUE THREAD

**Issue by micimize** [gql-dart/ferry#154]
I've published `*-nullsafety.1` versions of most `gql` packages,  so it is now safe to migrate `normalize` to null safety: https://github.com/gql-dart/gql/pull/194

Should be fairly straightforward using `dart migrate`

**Comment by smkhalsa** [comment]
@micimize awesome, thanks for doing that.

I'll try to work on this later this week.

**Comment by b-jan** [comment]
Hello @smkhalsa 
Did you have time to release a new version of `normalize` lib?

**Comment by smkhalsa** [comment]
@b-jan  [done](https://pub.dev/packages/normalize/versions/0.5.0-nullsafety.0)
