### ISSUE TITLE
generate graphql schema under current flutter 2.0.1 / dart 2.12.0

### ISSUE THREAD

**Issue by tshelver** [gql-dart/ferry#157]
Tryinng to use the ferry_generator, get the below.  Package seems to loop, tracing buck up the logs see:

[INFO] Running build...
[WARNING] gql_build:serializer_builder on lib/$lib$:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.10.0
SDK language version: 2.12.0

flutter packages upgrade
\Resolving dependencies...
  _fe_analyzer_shared 7.0.0 (17.0.0 available)
  analyzer 0.39.17 (1.1.0 available)

============================================

Only a single schema.gql.dart file is generated:

[schema.schema.gql.txt](https://github.com/gql-dart/ferry/files/6114608/schema.schema.gql.txt)

Input file is 
[schema.schema.gql.txt](https://github.com/gql-dart/ferry/files/6114613/schema.schema.gql.txt)

Thanks
Tony

**Comment by michaelspeed** [comment]
did you find out why is this happening?

**Comment by tshelver** [comment]
No, I didn't.  Going to go with a more manual approach, given the currently-low level of my expertise in Dart / Flutter.

One suspicion is that the GraphQL query generated by postgraphile doesn't represent what Ferry expects (use of input variables being the suspected culprit).  But not impossible that the V2.0 transition or my own incompetence affected things: just not got the time to track it down.

My entire backend is encapsulated in stored functions which are exposed via Postgraphile.  In my existing application, this works great through Python http calls using the GaphQL query held in a string, and using the python JSON library to convert the JSON to and from python dictionaries.

So will start there:  Most of the app's work will be in the UI and front end rather than accessing the backend data, some of which is my own via GraphQL, and some from mapping providers via REST interfaces.

I have been seeing a lot of negativity around some of the packages (google_maps_flutter being one) and required functionality, so maybe it's safest for me to go with the most used / best supported / lowest common denominator stuff first, and get my initial 'lite' app up and running before getting too fancy.

**Comment by gazialankus** [comment]
I had an infinite loop with Flutter 2 and these lines fixed it. Note that you cannot use the ^ before dart_style's version or it won't work.

```
dependency_overrides:
  analyzer: ^0.41.2
  dart_style: 1.3.13

dev_dependencies:
  build_runner: ^1.11.1
```
