### ISSUE TITLE
`BigInt` lost precision before deserialization

### ISSUE THREAD

**Issue by anthonychwong** [gql-dart/ferry#161]
Hi, I want to implement custom scalar deserializer for `bigint` (as #160 suggested), but before it comes to deserializer, it is already in `int`.

Is there anyway to process data before that point?

![image](https://user-images.githubusercontent.com/16477149/111744066-91bdc500-88c5-11eb-94ee-a4ab36336840.png)

**Comment by smkhalsa** [comment]
Are you sure your server is returning it as a string?

**Comment by anthonychwong** [comment]
I figured out how to tell Hasura to return `BigInt` quoted, so this works now.

**Comment by michaelspeed** [comment]
can you share how you fixed this with hasura?
