### ISSUE TITLE
ferry_generator is incompatible with build_runner >=1.12.0

### ISSUE THREAD

**Issue by ngallazzi** [gql-dart/ferry#163]
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  gql_link: ^0.3.1
  gql_http_link: ^0.3.2
  ferry: ^0.9.4
  ferry_hive_store: ^0.3.2
  ferry_flutter: ^0.4.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  get_it: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.12.2
  gql_build: ^0.1.4+2
  gql_code_builder: ^0.1.4+1
  ferry_generator: ^0.3.3

  flutter_test:
    sdk: flutter

**Error message:** Because every version of ferry_generator depends on build ^1.2.2 and build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0, ferry_generator is incompatible with build_runner >=1.12.0.
So, because app depends on both build_runner ^1.12.2 and ferry_generator ^0.3.3, version solving failed.

**Comment by smkhalsa** [comment]
Fixing `build_runner` to `1.10.1` should fix this for now.

**Comment by smkhalsa** [comment]
closing, but let me know if this issue persists
