### ISSUE TITLE
Cache update for paginated queries

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/ferry#166]
The current example for updating cache after a mutation shows a simple example, how do we update cache for paginated queries?

for example, if we are paginating queries to limit the page size to 10, do we have to iteratively go through the all different offsets for a specific query and update the cache?

**Comment by smkhalsa** [comment]
> for example, if we are paginating queries to limit the page size to 10, do we have to iteratively go through the all different offsets for a specific query and update the cache?

Yes, `ferry` doesn't know how your queries are connected (i.e. offset: 10 vs offset: 20).

If you have a suggestion for how we could improve this, please feel free to let us know.

**Comment by smkhalsa** [comment]
Closing, but feel free to provide any suggested changes.
