### ISSUE TITLE
Error on flutter web

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/ferry#168]
Running ferry on flutter web, Im getting the following linkException when i run a subscription:
`
ServerException(originalException: Unsupported operation: Platform._version, parsedResponse: null)
`

**Comment by smkhalsa** [comment]
Is this only happening on flutter web? What does your query and your schema look like?

**Comment by dopecoder** [comment]
Yes, this is happening only on flutter web and not on Android and IOS.

The query looks something like this : 

```
subscription getLatestSignalsUserS($uid:uuid!, $limit:Int, $offset:Int) {
  user_signal(where: {uid: {_eq: $uid}}, order_by: {signal: {modified_at: desc}}, limit: $limit, offset: $offset) {
    suid: id
    is_bookmarked
    is_traded
    sid
    uid
    signal {
      id
      created_at
      description
      down_votes
      ep
      is_algo
      is_pro
      modified_at
      position
      sec_currency
      sec_exchange
      sec_name
      sec_scrip
      sec_type
      sl
      tp1
      tp2
      tp3
      up_votes
      vid
      vid
      ltp
      status {
        id
        name
        created_at
        sid
      }
      vendor {
        fname
      }
    }
  }
}
```

its basically a typical subscription query over gql_websocket_link.

**Comment by smkhalsa** [comment]
> Yes, this is happening only on flutter web and not on Android and IOS.

In that case, there is probably an issue with your link, not with ferry itself
