### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by FlutterBoyfriend** [gql-dart/ferry#173]
This happens after I ran the download schema sdl [get-graphql-schema ENDPOINT_URL > lib/schema.graphql
]//With my endpoint url 

Even when I try to do it manually on playground 
I get 
![IMG_20210410_103203_153](https://user-images.githubusercontent.com/57899431/114265552-4ccf0f00-99e9-11eb-8761-cc46b1903549.jpg)

**Comment by smkhalsa** [comment]
It looks like this is related to Hasura, not ferry.

**Comment by FlutterBoyfriend** [comment]
> It looks like this is related to Hasura, not ferry.

Okay I'm just looking for a solution if you don't mind sir

**Comment by FlutterBoyfriend** [comment]
Okay I'm just searching for a solution I will be glad if you can help me
