### ISSUE TITLE
Cache including typename in the dataId always

### ISSUE THREAD

**Issue by tberman** [gql-dart/ferry#187]
I have run into some issues when attempting to use `readFragment` on a fragment defined on an interface where it is unable to locate the data in the cache because the cache creates ids that are `$typename:$id` and in `readFragment` (https://github.com/gql-dart/ferry/blob/master/normalize/lib/src/denormalize_fragment.dart#L68) the typename comes from the fragment type, which works great for object spreads but not for interface spreads.

My initial thought would be to allow/encourage a cache mode where the ids are globally unique, as that is the pattern I have seen elsewhere.

What do y'all think? Would a PR that creates such a mode be accepted?

**Comment by smkhalsa** [comment]
> My initial thought would be to allow/encourage a cache mode where the ids are globally unique, as that is the pattern I have seen elsewhere.

Can you expand on this? Can you provide an example?

My first impression would be to just swap lines [67 & 68](https://github.com/gql-dart/ferry/blob/master/normalize/lib/src/denormalize_fragment.dart#L68) so that you can pass the concrete `__typename` as an `idField`.

The interface `__typename` and entity ID are not enough to identify a unique entity, since multiple types which extend the same interface could have overlapping IDs.

**Comment by smkhalsa** [comment]
Also, `normalize` allows you to derive your own cache IDs using the [`dataIdFromObject`](https://github.com/gql-dart/ferry/blob/master/normalize/lib/src/denormalize_fragment.dart#L34) callback. However, we'd need update the `ferry_cache` to include it.

Using that approach, assuming your data has globally unique IDs, you could simply use the entity ID as the cache ID.

**Comment by tberman** [comment]
Yes, if lines 67 and 68 were swapped that would definitely allow me to override it and pass in __typename explicitly as a quick fix. Being able to include dataIdFromObject as part of the `readFragment` call would also do it!

My main question though is that most graphql implementations I have worked with the object id is globally unique by itself (mostly in service of supporting a relay style client), and I am wondering if it would make sense to explicitly support that mode instead of making the consumer do a lot of work to get that to happen?

**Comment by smkhalsa** [comment]
> most graphql implementations I have worked with the object id is globally unique

Do you mean the graphql server returns globally unique IDs for each entity? Or do you mean the client cache generates globally unique cache IDs?

If the latter, I'm curious which client caches you've used and what their approach is to generating unique cache IDs without using the `__typename` field. We follow the same approach as [Apollo Client](https://www.apollographql.com/docs/react/caching/cache-configuration/#generating-unique-identifiers).

> I am wondering if it would make sense to explicitly support that mode instead of making the consumer do a lot of work to get that to happen?

If we are assuming that our GraphQL server returns unique IDs across entities, and every entity has an `id` field, couldn't we achieve this by simply passing:

```dart
dataIdFromObject: (entity) => (entity as dynamic).id
```

Since GraohQL does not require unique IDs across entities, adding a mode that does have such a constraint seems brittle and use-case specific.

**Comment by tberman** [comment]
> > most graphql implementations I have worked with the object id is globally unique
> 
> Do you mean the graphql server returns globally unique IDs for each entity? Or do you mean the client cache generates globally unique cache IDs?

The former, they follow the relay graphql spec which provides a `Node` interface that guarantees that any id provided by a `Node` implementing object is globally unique, which allows the id itself to be used as a cache key.

> 
> If the latter, I'm curious which client caches you've used and what their approach is to generating unique cache IDs without using the `__typename` field. We follow the same approach as [Apollo Client](https://www.apollographql.com/docs/react/caching/cache-configuration/#generating-unique-identifiers).
> 

I have used both relay and apollo although I prefer the relay model for lots of reasons I am happy to articulate in another thread. The important thing here is that ferry isn't entirely following the Apollo Client, as the [possibleTypes](https://www.apollographql.com/docs/react/caching/cache-configuration/#possibletypes) cache configuration is how Apollo resolves the issue I am describing. You can see a bit of the implementation in the [`fragmentMatches`](https://github.com/apollographql/apollo-client/blob/cbcf951256b22553bdb065dfa0d32c0a4ca804d3/src/cache/inmemory/policies.ts#L581) code.

> > I am wondering if it would make sense to explicitly support that mode instead of making the consumer do a lot of work to get that to happen?
> 
> If we are assuming that our GraphQL server returns unique IDs across entities, and every entity has an `id` field, couldn't we achieve this by simply passing:
> 
> ```dart
> dataIdFromObject: (entity) => (entity as dynamic).id
> ```

Agreed, however this seems to be a deprecated and retired approach from [Apollo Client](https://www.apollographql.com/docs/react/caching/cache-configuration/#dataidfromobject) in favor of keyFields and possibleTypes providing fuzzy matching.

> 
> Since GraohQL does not require unique IDs across entities, adding a mode that does have such a constraint seems brittle and use-case specific.

It doesn't require it, but it does discuss this in its [best practices documentation](https://graphql.org/learn/global-object-identification/) and another popular graphql client library supports it natively, so this isn't an entirely out of left field idea.

Since ferry already leans into the Apollo model and embraces codegen, would it make sense to attempt to provide the fuzzy fragment matching capabilities by augmenting the request generator to include possible subtypes of a union/interface so the cache can use that to create potential keys? If that approach makes sense I am happy to find some time to work on a PR!

**Comment by smkhalsa** [comment]
Maybe I'm being dense, but I'm not sure I understand how the fuzzy matching approach solves this issue.

How does it disambiguate the `typename` when reading a fragment on an interface that has multiple concrete types with overlapping IDs?

**Comment by tberman** [comment]
> Maybe I'm being dense, but I'm not sure I understand how the fuzzy matching approach solves this issue.
> 
> 
> 
> How does it disambiguate the `typename` when reading a fragment on an interface that has multiple concrete types with overlapping IDs?

The overlapping ids are not relevant. The problem is objectTypes vs interfaceTypes and resolving fragments on interfaces when using `readFragment`. 

If your fragment is against an interface instead of an object type it will never find it using the current readFragment codepath as it assumes the type is always going to be an objectType. If you look at the code I linked in Apollo's cache you can see it attempts to create a dataId not only using the fragment's type but also possible sub types in order to help resolve it. 

My suggestion is if ferry wants to lean in to how Apollo does cache identity then something like possibleTypes needs to exist (and it seems like it could be generated for the user). 


Does that make sense? If not I can write up an example of the issue a bit more clearly (sorry, currently on my phone).

**Comment by tberman** [comment]
Alright, back at a computer. So consider the following SDL

```
interface Animal {
  name: String!
}

type Cat implements Animal {
  name: String!
}

type Dog implements Animal {
  name: String!
}

type Query {
  animals: [Animal!]
}
```

If you have a component that uses a fragment like:

```
fragment AnimalFragment on Animal {
  name
}
```

And attempt to use it with `readFragment` it will always look up with a dataId of `Animal:${id}` which is never going to work. Apollo solves this problem by supporting possible types and then not only looking up `Animal:${id}` but also `Cat:${id}` and `Dog:${id}` and relying on the chance of collisions being small. Relay solves this by going a different path and mandating that the `id` must be globally unique through the entire API so you don't need to prefix with the `__typename`. Both options make some sense and have different tradeoffs.

Either way, the current method looking up items in the cache using the interface typename from the fragment will never work given how ferry's caching works!

I agree that reversing lines 67 & 68 inside denormalize_fragment would allow a savvy user to pass in an explicit typename so likely that could _also_ be done, but I think its worthwhile to get `readFragment` to 'just-work' if at all possible.

Happy to spend some time attempting any of these changes presuming you are generally aligned on the approach and would be receptive to the PR!

**Comment by smkhalsa** [comment]
> Apollo solves this problem by supporting possible types and then not only looking up `Animal:${id}` but also `Cat:${id}` and `Dog:${id}` and relying on the chance of collisions being small

This is what I was trying to address in my previous comment. Although the `possibleTypes` approach would allow a fragment to be read on an interface, it only works reliably when there are globally unique IDs.

> I think its worthwhile to get readFragment to 'just-work' if at all possible.

I agree, but the only solutions I can think of are to:

1. **Assume Globally Uniqe IDs** - in this case, we could either generate `possibleTypes` based on the schema, or simply use the entity ID without the typename as the cache ID.
2. **Explicitly pass the `typename`** - This approach is not ideal because it requires the user to a) know the type of the desired entity, and b) remember to pass it in `readFragment`.
3. **Define a `dataIdFromObject` callback** 

The `dataIdFromObject` approach seems the most flexible to me, since it allows the user complete control over cache IDs, it's already implemented in `normalize` and would be easy to support in `ferry_cache`.

**Comment by tberman** [comment]
I don't think it would only work when there are globally unique ids. I think it would very likely work when the ids are not unique. In order for it to cause a collision, you would have to have:

1. Two objects with the exact same `id` field
2. That are both implementors of a specific interface
3. This interface has to be the one used to do the lookup for `readFragment`
4. They also need to have the same fields as the fragment's selection set

I am curious what Apollo does when it encounters this overlap? Quick read of relevant code (https://github.com/apollographql/apollo-client/blob/cbcf951256b22553bdb065dfa0d32c0a4ca804d3/src/cache/inmemory/readFromStore.ts#L183) makes me think it just flattens it out, but I am not sure, would have to dig in more.

`dataIdFromObject` definitely could do it, risk to me there is you are leaning into a deprecated API that likely is gone for good reason?

**Comment by smkhalsa** [comment]
> 4. They also need to have the same fields as the fragment's selection set

Why is this? If it implements the interface, it would have to have the same fields as the fragment's selection set? 

> `dataIdFromObject` definitely could do it, risk to me there is you are leaning into a deprecated API that likely is gone for good reason?

Although I definitely took inspiration from some of Apollo's APIs, I'm not trying to mirror Apollo. They deprecated `dataIdFromObject` in favor of `keyFields`, but there's no reason we need to follow suit.

**Comment by smkhalsa** [comment]
My main resistance as the sole maintainer of this package is expanding the API footprint if the issue could be resolved using the existing API.

**Comment by tberman** [comment]
> > 1. They also need to have the same fields as the fragment's selection set
> 
> Why is this? If it implements the interface, it would have to have the same fields as the fragment's selection set, right?
> 

You would have to have the same fields in the cache, otherwise the `readFragment` would return null. Using the example above, if Animal has `name` and `weight` and you happen to have the `Cat` with the `id` of `1` and a `Dog` with the `id` of `1` but you have only fetched the name on the Cat with an id of 1 and the fragment only asks for weight then it would only find the Dog instance when using `readFragment` as the selection set won't be the same. Not saying its impossible, just saying it becomes less and less likely once you fully evaluate the overlap required to trigger semi-defined behavior

> My main resistance as the sole maintainer of this package is expanding the API footprint if the issue can be resolved using the existing API.

Totally understand! I appreciate the discussion and getting on the same page on the problem and how to solve it before any code gets written, thank you! And thank you for a great library to even be discussing this about!

> Although I definitely took inspiration from some of Apollo's APIs, I'm not trying to mirror Apollo. They deprecated `dataIdFromObject` in favor of `keyFields`, but there's no reason we need to follow suit.

Oh, on that topic, I don't think that would solve this issue, because the issue here is getting the id from the fragment + idFields passed in, not the cache id. The id in the cache is fine enough, and in this case you don't have an `Object` to be the object in `dataIdFromObject`. Does that make sense?

**Comment by smkhalsa** [comment]
> I appreciate the discussion and getting on the same page on the problem and how to solve it before any code gets written

Definitely, me too

> You would have to have the same fields in the cache, otherwise the readFragment would return null. Using the example above, if Animal has name and weight and you happen to have the Cat with the id of 1 and a Dog with the id of 1 but you have only fetched the name on the Cat with an id of 1 and the fragment only asks for weight then it would only find the Dog instance when using readFragment as the selection set won't be the same. Not saying its impossible, just saying it becomes less and less likely once you fully evaluate the overlap required to trigger semi-defined behavior

Yes, but what if you're actually looking for the Cat? You would expect to get `null`, but instead you get a Dog. 

> Oh, on that topic, I don't think that would solve this issue, because the issue here is getting the id from the fragment + idFields passed in, not the cache id. The id in the cache is fine enough, and in this case you don't have an Object to be the object in dataIdFromObject. Does that make sense?

Not exactly. If `dataIdFromObject` is defined, it will be used when initially writing the data. Therefore, if you pass in that same ID in your `idFields`, it would correctly identify the entity.

**Comment by tberman** [comment]
> > You would have to have the same fields in the cache, otherwise the readFragment would return null. Using the example above, if Animal has name and weight and you happen to have the Cat with the id of 1 and a Dog with the id of 1 but you have only fetched the name on the Cat with an id of 1 and the fragment only asks for weight then it would only find the Dog instance when using readFragment as the selection set won't be the same. Not saying its impossible, just saying it becomes less and less likely once you fully evaluate the overlap required to trigger semi-defined behavior
> 
> Yes, but what if you're actually looking for the Cat? You would expect to get `null`, but instead you get a Dog.
>

Yup, that is _DEFINITELY_ a failure case here, but in theory if you have overlapping id spaces, you would get the same outcome with `dataIdFromObject`, so your are relying on globally unique ids or explicitly passing in the `__typename` as your only real solutions to this. More and more regardless of anything else, I think swapping lines 67 and 68 makes sense to at least let the caller override the type resolution behavior no matter what.
 
> > Oh, on that topic, I don't think that would solve this issue, because the issue here is getting the id from the fragment + idFields passed in, not the cache id. The id in the cache is fine enough, and in this case you don't have an Object to be the object in dataIdFromObject. Does that make sense?
> 
> Not exactly. If `dataIdFromObject` is defined, it will be used when initially writing the data. Therefore, if you pass in that same ID in your `idFields`, it would correctly identify the entity.

Interesting, so if you created the cache with a dataIdFromObject it would no longer create the id using the typename across the board? What about in the cases where you wouldn't want an override/returned null from dataIdFromObject? Not sure if that exists, but definitely not going to be able to figure that out in the `readFragment` codepath as you don't have an object to pass into the function.

**Comment by smkhalsa** [comment]
> I think swapping lines 67 and 68 makes sense to at least let the caller override the type resolution behavior no matter what

Agreed

> so if you created the cache with a dataIdFromObject it would no longer create the id using the typename across the board?

Yes, the cache key is whatever is returned by `dataIdFromObject`

> What about in the cases where you wouldn't want an override/returned null from dataIdFromObject?

If you are using global IDs, I'm not sure why you'd want to use both types of keys (i.e. only ID & `__typename` + ID). However, if you did, you could just concatenate them yourself in `dataIdFromObject` for those types.

> Not sure if that exists, but definitely not going to be able to figure that out in the readFragment codepath as you don't have an object to pass into the function

the way `readFragment` works is that it uses the `idFields` as the object, since those are the only relevent fields to identify the entity anyway.

**Comment by tberman** [comment]
Gotcha, this makes total sense! Want me to try to put together a PR for your review based on this discussion?

> > What about in the cases where you wouldn't want an override/returned null from dataIdFromObject?
> 
> If you are using global IDs, I'm not sure why you'd want to use both types of keys (i.e. only ID & `__typename` + ID). However, if you did, you could just concatenate them yourself in `dataIdFromObject` for those types.
> 

👍

**Comment by smkhalsa** [comment]
Sure!
