### ISSUE TITLE
No serializer for '_$GCreateLifeSessionVars'.

### ISSUE THREAD

**Issue by dokumanx** [gql-dart/ferry#188]
I am getting an error in the title. My request structure :

```dart

  Future<GCreateLifeSessionData_createLiveSession> createLifeSession(
      {String trainerId,
      String studentId,
      String startTime,
      String endTime,
      GLiveSessionType type}) async {
    OperationResponse response;

    try {
      final createLifeSession = GCreateLifeSessionReq((q) => q
        ..vars.trainerId.value = trainerId
        ..vars.studentId.value = studentId
        ..vars.start.value = startTime
        ..vars.end.value = endTime
        ..vars.type = type);
      response = await graphQlClient.request(createLifeSession).first;
      return response.data.createLiveSession;
    } catch (e) {
      print(response.graphqlErrors);
      return null;
    }
  }

```
And data that I have given to the `createLifeSession()` are:

![image](https://user-images.githubusercontent.com/48089386/118381093-03796d00-b5f0-11eb-85d0-e60853573f59.png)

Why am I getting this error?

**Comment by smkhalsa** [comment]
Is this a runtime error or an error when building the generated types?

Also, please share the schema (or at least the bits relevant to the above error).

Finally, please share the entire error you are getting.

**Comment by kulture-rob-snider** [comment]
I believe that I am getting a similar issue:

`type '_$GinsertMessageWithMediaVars' is not a subtype of type 'GinsertMessageWithMediaVars' of 'object'`

The error seems to be coming from built_value:
```
@override
Object? serializeWith<T>(Serializer<T> serializer, T? object) {
  return serialize(object, specifiedType: FullType(serializer.types.first));
}

@override
Object? serialize(Object? object, {FullType specifiedType = FullType.unspecified}) {
  var transformedObject = object;
  for (var plugin in serializerPlugins) {
    transformedObject = plugin.beforeSerialize(transformedObject!, specifiedType);
  }
  var result = _serialize(transformedObject, specifiedType); // <--- error thrown here
  for (var plugin in serializerPlugins) {
    result = plugin.afterSerialize(result, specifiedType);
  }
  return result;
}
```

The `object` coming is of type `_$GinsertMessageWithMediaVars`, but serializers.types.first is `GinsertMessageWithMediaVars`

**Comment by kulture-rob-snider** [comment]
I figured out the issue (at least for me). I am in the process of refactoring some stuff, and I had the same gql file in 2 directories. So, `type '_$GinsertMessageWithMediaVars' is not a subtype of type 'GinsertMessageWithMediaVars' of 'object'` was coming because one was from the generated file in dirA and one was from the generated file in dirB, so it is in fact not a subtype.

**Comment by smkhalsa** [comment]
Closing for now, but please reopen if this issue is still happening.

**Comment by biklas7** [comment]
@smkhalsa I have a similar problem, but for me is because I have a fragment and a query with the same name. Any suggestions?
