### ISSUE TITLE
Memory leak since version 0.4.3 of ferry_cache

### ISSUE THREAD

**Issue by friebetill** [gql-dart/ferry#189]
There has been a memory leak since version 0.4.3 of `ferry_cache`. 

When using 0.9.3 (`ferry`) the leak does not occur.
When using 0.9.4 (`ferry`) the leak occurs.

In 0.9.4 (`ferry`) the libraries `normalize` (`0.4.6` to `0.4.7`) and `ferry_cache` (`0.4.2` to `0.4.3`) were updated.
When using 0.4.6 (`normalize`) and 0.4.2 (`ferry_cache`) the leak does not occur.
When using 0.4.7 (`normalize`) and 0.4.2 (`ferry_cache`) the leak does not occur.
When using 0.4.6 (`normalize`) and 0.4.3 (`ferry_cache`), the app does not compile.
When using 0.4.7 (`normalize`) and 0.4.3 (`ferry_cache`), the leak occurs.
The two responsible commits are https://github.com/gql-dart/ferry/commit/8b2bb221a1e5b2cf6f44202ad5c0480d3fc45634 and https://github.com/gql-dart/ferry/commit/b40c660c39cd926292f316bcf785e19af127ea79.

Without the memory leak:
![image](https://user-images.githubusercontent.com/10923085/118391113-f631a200-b632-11eb-801e-89c6607368a8.png)
With the memory leak:
![image](https://user-images.githubusercontent.com/10923085/118391177-44df3c00-b633-11eb-9e56-7225ff7d208d.png)
After 1 minute:
![image](https://user-images.githubusercontent.com/10923085/118391200-63453780-b633-11eb-80dd-70fff80a0194.png)

I'm now trying to figure out what was changed in the commits and why, and where the leak is occurring.

These methods have been changed:
- `watchQuery`
- `watchFragment` (added)
- `fragmentDataChangeStream`
- `operationDataChangeStream` (previously `dataIdsChangeStream`)
- `fragmentDataId` (added)
- `reachableIdsFromDataId` (added)

If I only reset the methods `watchQuery` and `operationDataChangeStream` (`dataIdsChangeStream`) to the previous state, the memory leak is closed. 

If I revert only the computation of the variable `dataIds` in the method `dataIdsChangeStream` (`operationDataChangeStream`), the leak is closed (not sure whether leak is just smaller or closed).
Revert from 
```dart
  dataIds = reachableIdsFromDataId(
    rootTypename,
    optimistic ? optimisticReader : (dataId) => store.get(dataId),
  );
```
to
```dart
  var dataIds = <String>{};
  normalizeOperation(
    read: optimistic ? optimisticReader : (dataId) => store.get(dataId),
    write: (dataId, value) => dataIds.add(dataId),
    document: request.operation.document,
    operationName: request.operation.operationName,
    // TODO: don't cast to dynamic
    variables: (request.vars as dynamic)?.toJson(),
    data: (existingData as dynamic)?.toJson(),
    typePolicies: typePolicies,
    addTypename: addTypename,
  );
```

I have now looked at which IDs the variable `dataIds` has. And in the old code it has 2, 3, 4 or 5 IDs (for different requests) and in the new code always 480 IDs. This contradicts a bit the hypothesis that it is a memory leak and rather suggests that simply a lot space for streams are allocated. An alternative is that the memory consumption of 2-5 streams is not as noticeable as with 480 streams and it is still a memory leak. 

#### What should the operationDataChangeStream method do?

The method watches the database for all nodes of a given request and as soon as one node changes it returns the ID of the node. 

The function can be divided into three parts:
1. Get the data IDs that need to be watched for the given request:
  ```dart
  final operationDefinition = getOperationDefinition(
    request.operation.document,
    request.operation.operationName,
  );
  final rootTypename = resolveRootTypename(
    operationDefinition,
    typePolicies,
  );
  final dataIds = reachableIdsFromDataId(
    rootTypename,
    optimistic ? optimisticReader : (dataId) => store.get(dataId),
  );
  ```
2. Get a watch stream for each id (node):
  ```dart
  /// Streams for each dataId referenced in data, including the [rootTypename]
  final streams = dataIds.map((dataId) {
    var stream = dataForIdStream(
      dataId,
      store,
      optimistic,
      optimisticPatchesStream,
      optimisticReader,
    );

    /// we only want to subscribe to changes on the operation fields, not the entire operation type)
    if (dataId == rootTypename) {
      stream = stream.map(
        (data) => operationRootData(
          data,
          request,
          typePolicies,
        ),
      );
    }

    return stream
        .distinct(
          (prev, next) => const DeepCollectionEquality().equals(
            prev,
            next,
          ),
        )
        .doOnData((_) => changed.add(dataId));
  });
  ```
3. Merge the streams and return a new event when at least one node changes:
  ```dart
  return CombineLatestStream<Map<String, dynamic>?, Set<String>>(
    streams,
    (_) {
      final result = {...changed};
      changed.clear();
      return result;
    },
  )

      /// Skip the first result since this returns the existsing data
      .skip(1);
  ```

#### Where is the problem?

The problem is, as far as I understand it, in the first part. To get the IDs of the nodes this part traverse the whole "database tree". Each time a node contains the key `\$ref` and is not yet in the `dataIDs` set, the node is added to the set. Also, every time the node contains `\$ref` the node is read from the database and is also traversed. The problem is that the database tree looks like this for me: 
```json
{
  "__typename": "Query",
  "viewer": {
    "$ref": "User:{\"id\":\"cklpc43mb00424smro9knymyk\"}"
  },
  "trainer({\"id\":\"cko4bbl5v736464splgnew0fam\"})": {
    "$ref": "Trainer:cko4bbl5v736464splgnew0fam"
  },
  "trainer({\"id\":\"cko4bbgnh736134splucgqx0mw\"})": {
    "$ref": "Trainer:cko4bbgnh736134splucgqx0mw"
  }
  ...
}
``` 
Because each node has `\$ref` as key, all IDs are added to `dataIDs` and are also read from the database. Naively, I think the method should not start at the root, but at the root node of the query. The problem is that there is (I think) no mapping between a query and the response nodes.

In the previous version 0.4.2 (`ferry_cache`) the problem was solved by passing the query response (`existingData`) as an additional argument to `operationDataChangeStream`. Then `existingData` could be normalized and we got the IDs of the nodes. I don't know yet why this approach was replaced. A disadvantage of this method is that one has to pass `existingData` as an argument. To avoid the argument, one simple way would be to make the read of the cached response in the method itself:
```dart
final existingData = readQuery(
  request,
  optimistic: optimistic,
);
```

**Comment by smkhalsa** [comment]
@friebetill Thanks so much for tracking this down.

#192 should fix the issue causing all data IDs to be tracked. I added a test, but please confirm this is resolved for you as well.

**Comment by friebetill** [comment]
Yes the problem is fixed now! Thanks for your speedy fix!

**Comment by smkhalsa** [comment]
Great! 

Please let me know if you find any other performance issues. I know there is room for improvement.
