### ISSUE TITLE
Cache update with optimisticResponse

### ISSUE THREAD

**Issue by awaik** [gql-dart/ferry#19]
### Description

During diving into the code for https://github.com/gql-dart/ferry/issues/18, I found some problems with the cache update with optimisticResponse.

If we make the mutation with Optimistic Response

```
final mutation = ProfileBmiMutation2(
  buildVars: (b) => b..input = profileInput,
  updateCacheHandlerKey: IdCacheHandlers.profileBmiMutation,
  optimisticResponse: optimisticRequest,
).copyWith(
  context: Context.fromList(
    [
      HttpLinkHeaders(
        headers: idToken,
      ),
    ],
  ),
);
client
    .responseStream(mutation)
    .firstWhere((response) => response.optimistic)
    .then((response) {});
```
cache updates incorrectly.

### Assumption where the bug is

Maybe it is connected with code here `/lib/src/cache/cache_proxy.dart`, because if we change `optimistic: _optimistic,` to `optimistic: false,` it starts to work correctly (in this exact use-case).
I guess, there is more logic. I just pointed out what I've found.

```
  void writeQuery(
    Request request,
    Map<String, dynamic> data,
  ) =>
      _cache.writeQuery(
        request,
        data,
        optimistic: false,
        queryId: _queryId,
      );
```

### Screenshot

1. When we make the first request cache is not updated. 
2. But if we open the screen again, cache updates.
3. After that, other updates do not change the cache.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5330807/79063602-4ddb3c80-7cc0-11ea-895e-1719744ba9a3.gif)

**Comment by smkhalsa** [comment]
@awaik can you add a failing test for this, and I'll take a look?

**Comment by awaik** [comment]
@smkhalsa ok, I do it after finishing the example with mutations
