### ISSUE TITLE
Not generating dart files after upgrade

### ISSUE THREAD

**Issue by sumitsharansatsangi** [gql-dart/ferry#190]
When I was using null-safety pre-release version of this package everything was fine, but after upgrading it is not generating any file. 
![Screenshot at 2021-05-17 14-12-47](https://user-images.githubusercontent.com/45959281/118460307-18d3c180-b6ec-11eb-934d-ee5be6d50ea5.png)

**Comment by friebetill** [comment]
It looks like your files have already been generated and therefore they are not regenerated. You can enforce this by executing cleaning your cache: 
```
flutter clean
find . -name "*.g.dart" -type f -delete
find . -name "*.gql.dart" -type f -delete
```

**Comment by sumitsharansatsangi** [comment]
But in my graphql there is only schema.graphql file is there.

**Comment by sumitsharansatsangi** [comment]
I have tried whatever you have said, but still no output is generated.

**Comment by friebetill** [comment]
What was the problem and how did you solve it?

**Comment by sumitsharansatsangi** [comment]
Works when I created  new  project.
