### ISSUE TITLE
From Stream to Future ? BLoC/Repository/ApiProvider pattern

### ISSUE THREAD

**Issue by dleurs** [gql-dart/ferry#197]
Hello !

I would like to use Ferry, but I do not want to use the ```Operation<XData, XVars>(client: client, operationRequest: req, ``` mecanism using streams.

Instead, I would like to use BLoC state management, create a ```TodoApiProvider``` with a function ```Future<List<Todo>> getTodos() async {``` that will be called inside ```TodosBloc``` whenever the event ```GetTodos``` is called, returning the event ```GetTodosSuccess(await _repository.getTodos())```.

But to do so, in ```TodoApiProvider```, I need to switch from a Stream to a Future :
```
class TodoApiProvider {
  final client = initClient("http://localhost:1337/graphql"); // Strapi locally

  Future<List<Todo>> getTodos() async {
    final reqGetTodos = GGetTodosReq();
    List<Todo> todos = [];
    await for (var value in client.request(reqGetTodos)) {
      if (value.data != null && value.data!.todos != null) {
        for (var todo in value.data!.todos!) {
          print(todo);
          todos.add(Todo(id: int.parse(todo.id), name: todo.name));
          print(todos);
        }
      }
    }
    return todos;
  }
}
```
With this, the ```print(todos)``` actually shows all my todos, but it seems like the ```await for (var value in client.request``` loop is never ending, leaving the screen of my app on ```Loading``` where todos should be displayed.

I used to work with Artemis for flutter graphql but it is not yet null-safety.

Thank you very much :)

**Comment by smkhalsa** [comment]
This seems like a question for StackOverflow since it doesn't seem to actually be related to ferry but rather dart streams in general.

In any case, take a look at the `first` and `firstWhere` methods on dart streams

**Comment by dleurs** [comment]
Yes thank you .first work, don't know why I didn't get it right before and tried using await for
```
  Future<List<Todo>> getTodos() async {
    final reqGetTodos = GGetTodosReq();
    List<Todo> todos = [];
    var value = await client.request(reqGetTodos).first;
    if (value.data != null && value.data!.todos != null) {
      var gqlTodos = value.data!.todos!;
      for (var todo in gqlTodos) {
        print(todo);
        todos.add(Todo(id: int.parse(todo.id), name: todo.name));
        print(todos);
      }
    }
    return todos;
  }
```

**Comment by c-lamont** [comment]
Disclaimer; I'm new so could be talking rubbish.

@dleurs I'm not sure if this is a good solution. For me, just using `first` returned a cached version of the response.

I am now using;
```
    final response = await ferryGraphQl.client
        .request(request)
        .firstWhere((element) => !element.loading);
```

It has always worked for me so far but I'm not really comfortable with it. 
I'm surprised this is not common request with Ferry, as using the provided widgets to directly call an API feels like a bad practise, especially when using a clean architecture.
