### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by sumitsharansatsangi** [gql-dart/ferry#198]
I am not sure whether this library support for file upload or not, because I didn't find regarding this in the documentation.  If it supports please mention in the documentation with an example ,if it doesn't please provide support for it.

**Comment by smkhalsa** [comment]
There isn't really a canonical method for file uploads in GraphQL. See this [discussion](https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/) from Apollo. Each method has its advantages and drawbacks.

In any case, `ferry` should be able to support whatever you choose, but it will require some configuration, mostly on the server side.

**Comment by p02diada** [comment]
Hi @sumitsharansatsangi  , I have written an article in medium explaining how to do it: https://link.medium.com/gIJHjREi8hb
