### ISSUE TITLE
Error: 'update' is already declared in this scope.

### ISSUE THREAD

**Issue by trevhud** [gql-dart/ferry#203]
I'm getting an error when I try to run in debug mode that "Error: 'update' is already declared in this scope."

I only have one update mutation and it looks like this:

`mutation UpdateHarvestGroup($harvestGroup: UpdateHarvestGroup!) {
  HarvestGroup {
    update(input: $harvestGroup) {
      id
    }
  }
}`

This is occurring in my **.data.gql.g.dart file so it's a generated file.

I don't really have much to go on as this was generated from my graphQL schema and queries, which did not present an error before running. Happy to add more detail, just not sure what's relevant. Thanks for the help!

**Comment by smkhalsa** [comment]
This is likely related to https://github.com/gql-dart/gql/issues/222

**Comment by trevhud** [comment]
@smkhalsa Thank you!

**Comment by smkhalsa** [comment]
@trevhud can you confirm that https://github.com/gql-dart/gql/pull/223 resolved this issue?

**Comment by trevhud** [comment]
@smkhalsa confimed
