### ISSUE TITLE
Proposal: Merge as many as possible generated files per query

### ISSUE THREAD

**Issue by hazzo** [gql-dart/ferry#210]
Hello, first of all cool package and thanks for your contribution!

I got a question that is more like a proposal. It would be possible to merge as many generated files as possible per query? I mean is necessary that `*.data.gql.dart` and `*.data.gql.g.dart` are separated files? My guess is that you are generating `*.data.gql.dart` and `*.data.gql.g.dart` it's been generated by other dependency, right? Or there is another reason for this code to be split in similar files?

**Comment by smkhalsa** [comment]
Yes, the `*.gql.g.dart` files are generated from the `*.gql.dart` files by the `built_value` package.

**Comment by smkhalsa** [comment]
We recommend putting your `.graphq` query files into a `/graphq` directory to keep them separate from your other dart code.

**Comment by hazzo** [comment]
Thanks @smkhalsa, yes I'm actually putting each query in a separate subdirectory to avoid navigating through too many files. I will try to take a look to the repo if I can contribute in something to reduce the amount of files generated. Which repo should I look? `ferry_generator` right?

**Comment by smkhalsa** [comment]
`ferry_generator` is responsible for the `.req` files, but `gql_build` is responsible for the rest.
