### ISSUE TITLE
Generate dart classes based on schema definitions

### ISSUE THREAD

**Issue by 1awaleed** [gql-dart/ferry#211]
I am wondering if `ferry` or any other tool in dart ecosystem is capable in any way of generating types based on schema definitions? I cannot seem to find any documentation or related questions on this.

for example:

Given the following piece of scheme:
```dart
type Person {
    age: Int
    name: String!
}
```
Can it be converted to sound null safe dart class like this:
```dart
class Person{
  int? age;
  String name;

  Person({this.age, required this.name});

  Person.fromJson(Map<String, dynamic> json){
    age = json['age'];
    name = json['name'];
  }

  Map toJson(){
    Map _data = {};
    _data['age'] = age;
    _data['name'] = name;
    return _data;
  }
}
```

**Comment by smkhalsa** [comment]
Ferry's generated data types only include the fields defined by their respective queries.

The only way to generate a class with all fields defined in the schema would be to define a query with each of those fields.

I'm curious, what is your use case?

You may also want to check out `artemis`.

**Comment by 1awaleed** [comment]
First of all thanks for the fast reply and the awesome project.
Actually this was the default behaviour in a generator I used in JS for a some time but I actually do not have a current use case and I do not think I will have one.
