### ISSUE TITLE
How to work with OptimisticResponse for mutations?

### ISSUE THREAD

**Issue by warcayac** [gql-dart/ferry#216]
I wish to use OptimisticResponse for my mutation which is:
```
mutation UpdateCompleted($id: Int!, $isCompleted: Boolean!) {
	update_todos_by_pk(
		pk_columns: { id: $id }
		_set: { is_completed: $isCompleted }
	) {
		id
		title
		is_completed
	}
}
```
The class generated for this operation is `GUpdateCompletedReq`, and the Dart code to use it is:
```
final _updateCompleted = GUpdateCompletedReq((b) => b
  ..vars.id = item.id
  ..vars.isCompleted = !item.is_completed
);
```
According to the [Ferry documentation](https://ferrygraphql.com/docs/mutations#optimistic-updates) I should (apparently) add these lines:
```
  ..optimisticResponse.update_todos_by_pk.id = '__optimistic__'
  ..optimisticResponse.update_todos_by_pk.is_completed = !item.is_completed
```
but `id` is an integer type so an error message is raised. Actually I don't know what I'm doing 'cause there's no many full examples and the explanation is unclear, IMHO.

How should I correctly use OptimisticResponse?

**Comment by smkhalsa** [comment]
> but `id` is an integer type so an error message is raised.

So make it an integer.

**Comment by smkhalsa** [comment]
> the explanation is unclear, IMHO.

PRs welcome to the [docs repo](https://github.com/gql-dart/ferry-docs)

**Comment by warcayac** [comment]
Thanks for your answer @smkhalsa , my confusion was 'cause to this line in the documentation:
```
   ..optimisticResponse.createReview.id = "__optimistic__"
```
Pimary keys are usually integers or uuids but WHY do they set a string for `id` field? is it a special setting for OptimisticResponse? or is it simply an error?

**Comment by smkhalsa** [comment]
> is it a special setting

No, there is nothing special about fields that are named "id". You just need to return whatever optimistic data you want that matches the structure of your schema.

In the case of the example in the docs, `createReview.id` is assumed to be a string, so we are just passing a placeholder that wouldn't collide with an ID already present in the cache.

BTW, the GraphQL ID type is serialized as a string, so I'm not sure why you'd assume that all fields named "id" would be integers.
