### ISSUE TITLE
Union types prevent generator form generating response data types

### ISSUE THREAD

**Issue by EhabSalah** [gql-dart/ferry#220]
I am trying to run the following query, but upon running the ferry code generator, all the fields that are of type `Image` or `Flagged` or `Hidden` does not get generated and all the generator generate for the query result is the `id` and the `name`.
```graphql
query user($id:String!){
    user(id: $id){
        id
        name
        ... on Image{
            id
        }
        ... on Flagged{
            reason
        }
        ... on Hidden{
            message
        }
    }
}
```

I had to overcome this limitation by using the `toJson()` function on the data from the generator. But is there a way to make the generator understand that those fields are `optionals` ? or is this a current limitation in the ferry generator?

**Comment by smkhalsa** [comment]
The generator generates separate classes for each fragment spread.

For example, you should have a class called something like `Guser_user__asImage`.

Ferry is smart enough to manually instantiate the correct class based on the `__typename` of the data during deserialization.

**Comment by 1awaleed** [comment]
Hello @smkhalsa I also have the same problem but I cannot find an example on how to utilize those classes.
If i have the above query and try to run the request as follows:

```dart
   final queryResult = await client.request(GUserReq()).first;
```
The `result` is of type `GUserData` which have the fields `id` and `name` only as class properties.

**Comment by smkhalsa** [comment]
Does your GraphQL server respond with the exact __typename that's used in the fragment spread?

Ferry uses the __typename to deserialize into the correct type.

**Comment by 1awaleed** [comment]
@smkhalsa Yes, my server responds with the exact __typename used in the fragment. How should I utilize it since the GUserData does not contain the missing properties?

**Comment by smkhalsa** [comment]
The generator will create a base class with just the fields not in an inline fragment, and an additional class for each inline fragment.

**Comment by 1awaleed** [comment]
Ahhh thanks @smkhalsa  .. Here is what I understood: 

My query looks like this
```graphql
query getUser($id:String!){
    user(id: $id){
        id
        name
        imageResult{
            ... on Image{
                id
            }
            ... on Flagged{
                reason
            }
            ... on Hidden{
                message
            }
        }
    }
}
```

And this is how I consume the query, Do you have any more suggestions?

```dart
    final res = await client.request(req).first;

    if (res.data != null) {
      final imageRes = res.data?.user.imageResult;

      if (imageRes is GgetUserData_imageResult__asImage){
          // fetch image with ID
          imageRes.id;

      } else if( imageRes is GgetUserData_imageResult__asFlagged){
          // show user reason image is flagged
          imageRes.reason;

      } else if( imageRes is GgetUserData_imageResult__asHidden){
          // Hide image from user
          imageRes.message;
      }
      
    } 
```
