### ISSUE TITLE
How to override Upload scalar to MultipartFile?

### ISSUE THREAD

**Issue by dokumanx** [gql-dart/ferry#221]
I followed instructions in official doc. I created custom serializer which is called `FileSerializer`. It overrides `Upload` scalar to `MultipartFile`. But in advance, I get a null response when I use it to upload an image.

**My custom serializer:**

``` dart
import 'package:built_value/serializer.dart';
import 'package:http/http.dart';
import 'package:http_parser/http_parser.dart';

class FileSerializer implements PrimitiveSerializer<MultipartFile> {
  @override
  MultipartFile deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is List<int>,
        "FileSerializer expected 'List<int>' but got ${serialized.runtimeType}");
    return MultipartFile.fromBytes(
      'photo',
      serialized as List<int>,
      filename: '${DateTime.now().millisecondsSinceEpoch}.jpg',
      contentType: MediaType("image", "jpg"),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    MultipartFile file, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      file;

  @override
  Iterable<Type> get types => [MultipartFile];

  @override
  String get wireName => "Upload";
}
```

**uploadProfilePicture():**
```dart
  Future<GUploadProfilePictureData> uploadProfilePicture(
      {required String userId, required http.MultipartFile file}) async {
    late final OperationResponse response;
    try {
      final uploadProfilePicture = GUploadProfilePictureReq((q) => q
        ..vars.userId = userId
        ..vars.file = file);
      response = await graphQlClient.request(uploadProfilePicture).first;
      return response.data;
    } catch (e) {
      print(response.graphqlErrors);
      throw Exception(e.toString());
    }
  }
```
And one last thing that bothers me: `serialized as List<int>` in the `FileSerializer`. This is the `Uint8List` which is gotten by calling `readAsBytesSync ()` on a file. So, if we expect to serialize `MultipartFile`, why do we use `serialized as List<int>`? In this case, I assume that we actually serialize `serialized as List<int>` then use it to return `MultipartFile`. By the way, `FileSerializer` is an example that I found out in the ferry discord channel. I am not sure it is the correct approach to override `MultipartFile`

**Comment by dokumanx** [comment]
Any idea?

**Comment by p02diada** [comment]
Hi @dokumanx , I have written an article in medium explaining how to do it: https://link.medium.com/gIJHjREi8hb

**Comment by dokumanx** [comment]
> Hi @dokumanx , I have written an article in medium explaining how to do it: https://link.medium.com/gIJHjREi8hb

Hi, I have just checked it out. It seems detailed. I will try. Thanks for your reply.

**Comment by p02diada** [comment]
yaw! Let me know if you achieve it or if I can help you

**Comment by p02diada** [comment]
> > Hi @dokumanx , I have written an article in medium explaining how to do it: https://link.medium.com/gIJHjREi8hb
> 
> Hi, I have just checked it out. It seems detailed. I will try. Thanks for your reply.

yaw! Let me know if you achieve it or if I can help you

**Comment by smkhalsa** [comment]
Closing this since it doesn't appear there is any issue.

Feel free to use the discord if you have other questions.
