### ISSUE TITLE
EnumClasses support fallback with Graphql API Schema Updates

### ISSUE THREAD

**Issue by Nealsoni00** [gql-dart/ferry#228]
On the Apollo Graphql clients, when an enum is returned from the graphql and serialized, there is always a fallback enum option. In Android that fallback enum value is `UNKNOWN__`.

 This unknown fallback value allows for future-proofing the current app release for potential updates to the schema (for example adding a new value to the enum). Right now, when a unknown enum value is returned by the server, it throws an `ArgumentError` which would not allow adding new values to the enum in future versions of the Graph API.

It would be very helpful if in the generation process this unknown value was adding to the EnumClass -- specifically the generated `_$g<NameOfEnum>ValueOf` method.

**Comment by smkhalsa** [comment]
This is already implemented. Did you read the docs for gql_build?

https://github.com/gql-dart/gql/blob/d3780d564739db313ed2027a5bf3d51abba8ecd1/codegen/gql_build/README.md#configuration

**Comment by Nealsoni00** [comment]
Amazing thank you for pointing out that flag. Love ferry a lot -- it's v clear you all spent a lot of time architecting it!
