### ISSUE TITLE
How to mock response for testing?

### ISSUE THREAD

**Issue by kartik1225** [gql-dart/ferry#229]
Everything is great so far but I am stuck with mocking the response.

For example, I am using a library like `Mockito` to mock the response. Then from JSON how I can mimic the response?

e.g. in `http.Client` we can mock the response like `http.Response('Not Found', 404)` 

But I am not able to figure out how to do with this library so far!

**Comment by smkhalsa** [comment]
All of the ferry data classes have toJSON / fromJSON methods

**Comment by kartik1225** [comment]
@smkhalsa Thank you so much for a very quick response!

I am using [mockito](https://github.com/dart-lang/mockito) library to [generate mocks](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#custom-generated-mocks).

Yes, I can see the `toJson` / `fromJSON` And I have tried something:

```
@GenerateMocks([
  Client // Generate MockClient class
], customMocks: [
  MockSpec<OperationResponse<GEpisodesData, GEpisodesVars>>(as: #MockResponse) // Generate typed OperationResponse as MockResponse class
])
void main() {
  late MockClient mockClient;
  late MockResponse mockResponse;

  setUp(() {
    mockClient = MockClient();
    mockResponse = MockResponse();
  });

  GEpisodesData? getFakeData(){
    final jsonData = fixture("fixture_episodes.json"); // string data of `client.request(req).first->data->toJson`
    return GEpisodesData.fromJson(json.decode(jsonData));
  }

  test('should return success response',() async {
    when(mockResponse.data).thenReturn(getFakeData());
    when(mockClient.request(any).first) // <- throwing error here 
        .thenAnswer((realInvocation) => Future.value(mockResponse));
    // then expect and stuff...
  });
}
```

But this test is throwing error:

```
dart:async                                                        Stream.first
test/data/remote/rick_and_morty_data_source_impl_test.dart 38:34  main.<fn>
test/data/remote/rick_and_morty_data_source_impl_test.dart 36:41  main.<fn>

Bad state: No element
```

I think it is related to `mockClient.request(any)` is being null or something not sure

Any example would be much helpful 
Thanks

**Comment by smkhalsa** [comment]
You can see the Ferry's [tests](https://github.com/gql-dart/ferry/blob/master/ferry/test/typed_links/gql_typed_link_test.dart) for some guidance.

Otherwise, I suggest asking around on the discord.

**Comment by nailkhasipov** [comment]
I think any example here really could help a lot

**Comment by glupeksha** [comment]
Yeah, The link provided was not available. It would be really helpful if we could see an example test case in here or in PokemonExplorer.

**Comment by smkhalsa** [comment]
> You can see the Ferry's [tests](https://github.com/gql-dart/ferry/blob/master/packages/ferry/test/typed_links/gql_typed_link_test.dart) for some guidance.
> 
> Otherwise, I suggest asking around on the discord.

I updated the link above

**Comment by nailkhasipov** [comment]
Here is working example, i am testing `fetchActiveSessions` method of my ActiveSession class that call client.request and returns list of currently using devices (iphone, android) in chat app.

```
// Generate a MockClient using the Mockito package.
// Create new instances of this class in each test.
@GenerateMocks([
  Client
], customMocks: [
  MockSpec<OperationResponse<GActiveSessionListData, GActiveSessionListVars>>(
      as: #MockResponse) // Generate typed OperationResponse as MockResponse class
])
void main() {
  group('ActiveSessionList', () {
    test(
        'returns an ActiveSessionList if the query call completes successfully',
        () async {
      final client = MockClient();
      final mockResponse = MockResponse();

      final file = File('test/active_sessions_test.json');
      final jsonData = await file.readAsString();

      GActiveSessionListData? getTestData() {
        return GActiveSessionListData.fromJson(json.decode(jsonData));
      }

      when(mockResponse.data).thenReturn(getTestData());

      when(client.request(GActiveSessionListReq()))
          .thenAnswer((_) => Stream.fromFuture(Future.value(mockResponse)));

      var activeSessions = ActiveSessions(client);

      expect(await activeSessions.fetchActiveSessions(),
          isA<List<ActiveSession>>());
    });
  });
}
```

**Comment by RickZzDev** [comment]
I was having the same problem, and for me it was not the serializer on build.yaml, cause it was already there. My problem was the json that i was sending to from json, i just copy and paste the response of my back end from insmonia, and it was like this 
{
  "data": {
    "movies": {
      "currentPage": 0,
      "lastPageIndex": 3,
      "pageSize": 10,
      "movies": [
        {
          "id": "29912966"
        }
      ]
    }
  }
}

But the fromJson method was giving that same error and putting null on my field that should be populated with thoose datas. TO SOLVE it, i just need to add the field '__typeName' that i suppose the ferry does it by his self, and remove the field 'data', and my mock json was updated to that

{
    "__typename": "Query",			
    "movies": {
     "__typename": "MoviesModel",
      "currentPage": 0,
      "lastPageIndex": 3,
      "pageSize": 10,
      "movies": [
        {
          "id": "29912966"
        }
      ]
    }
}

And worked :)
