### ISSUE TITLE
Unable to build generate classes on mac os

### ISSUE THREAD

**Issue by gairick-saha** [gql-dart/ferry#230]
[SEVERE] built_value_generator:built_value on lib/schema/schema.schema.gql.dart:
Error in BuiltValueGenerator for /incredible/lib/schema/schema.schema.gql.dart.
Please make the following changes to use built_value serialization:

1. Declare GENUM_JOB_VISIBILITY.serializer as: static Serializer<GENUM_JOB_VISIBILITY> get serializer => _$gENUMJOBVISIBILITYSerializer; got static Serializer<GENUM_JOB_VISIBILITY> get serializer => _$genumJobVisibilitySerializer;
2. Declare GENUM_JOB_PAYMENT_TYPE.serializer as: static Serializer<GENUM_JOB_PAYMENT_TYPE> get serializer => _$gENUMJOBPAYMENTTYPESerializer; got static Serializer<GENUM_JOB_PAYMENT_TYPE> get serializer => _$genumJobPaymentTypeSerializer;
3. Declare GENUM_PRODUCT_TYPE.serializer as: static Serializer<GENUM_PRODUCT_TYPE> get serializer => _$gENUMPRODUCTTYPESerializer; got static Serializer<GENUM_PRODUCT_TYPE> get serializer => _$genumProductTypeSerializer;
4. Declare GENUM_USERSPERMISSIONSUSER_PREFERED_CHARGING_TYPE.serializer as: static Serializer<GENUM_USERSPERMISSIONSUSER_PREFERED_CHARGING_TYPE> get serializer => _$gENUMUSERSPERMISSIONSUSERPREFEREDCHARGINGTYPESerializer; got static Serializer<GENUM_USERSPERMISSIONSUSER_PREFERED_CHARGING_TYPE> get serializer => _$genumUserspermissionsuserPreferedChargingTypeSerializer;
5. Declare GENUM_USERSPERMISSIONSUSER_PREFFERED_WORK_LOCATION.serializer as: static Serializer<GENUM_USERSPERMISSIONSUSER_PREFFERED_WORK_LOCATION> get serializer => _$gENUMUSERSPERMISSIONSUSERPREFFEREDWORKLOCATIONSerializer; got static Serializer<GENUM_USERSPERMISSIONSUSER_PREFFERED_WORK_LOCATION> get serializer => _$genumUserspermissionsuserPrefferedWorkLocationSerializer;
[INFO] 42.0s elapsed, 70/72 actions completed.
[INFO] 43.2s elapsed, 96/96 actions completed.
[INFO] Running build completed, took 43.8s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 397ms

**Comment by Prathik-Jain** [comment]
https://github.com/gql-dart/gql/issues/239

**Comment by smkhalsa** [comment]
Closing since this appears to be related to the above linked issue.
