### ISSUE TITLE
Very long build times

### ISSUE THREAD

**Issue by QuirijnGB** [gql-dart/ferry#238]
The app that we're working on uses Ferry to talk to the Shopify GraphQL API.
We implemented it and it all works. 
What we did notice is:
* The generated code is around 600k lines. 
* Android release build has shot up to 30min on a Ryzen9 machine.
* iOS release build is around 50min on a macbook pro.
* The builds time out on Github actions (6 hours)

These build times are also the case when just having the generated files in the project without using them.
Verbose logging during builds don't surface any issues

I've run out of ideas on how to further debug/fix this issue so any pointers are welcome :smile: 
Cheers!

**Comment by smkhalsa** [comment]
duplicate of https://github.com/gql-dart/ferry/issues/143

**Comment by QuirijnGB** [comment]
This is not the build_runner, although that takes a while too. Its the app production builds

**Comment by smkhalsa** [comment]
Ah, yes. Reopening.

**Comment by smkhalsa** [comment]
The project I'm working on has ~300k lines of generated ferry-related code, and it takes about 20 minutes for my app to build for iOS with Github Actions, so 6 hours for 600k seems unusual.

About ~3/4 of the generated code is from built_value (to get the serializers, builders, and immutability features), so I don't believe there's a whole lot we can do at the moment to bring that down. The Dart team is considering some language features which, if added, could allow for us to eliminate built_value altogether, but that is probably not coming soon.

Although ferry only generates data classes for the operations that are used, there is some schema-related code that may be superfluous, so you may get some modest gains if you prune your schema to only what is being used.

**Comment by QuirijnGB** [comment]
Interesting, our used to be around the 20min mark before a PR with around 300k lines added.

Ill have a look if i can strip something. Otherwise i might have to consider an alternative :/

**Comment by QuirijnGB** [comment]
Managed to prune the `.graphql` removing around 400k generated lines :ok_hand: 
Builds on my Ryzen9 back down to 9min.
Lesson: Know your schema :+1:
