### ISSUE TITLE
Flatten nested object

### ISSUE THREAD

**Issue by ValentinVignal** [gql-dart/ferry#239]
Let's say I have the GraphQL query:

```graphql
query profilePictureId {
  user {
    profile {
      media {
        picture {
          id
        }
      }
    }
  }
}
```

I only want the profile picture but I end up with a deep nested object and I have not choice but access it with `profilePictureId.user.profile.media.picture.id`.

Is there a way to manipulate the graphql file so I end up with an object `profilePictureId.id` as if my query would have been:

```graphql
query profilePictureId {
  id
}
```

Like those packages are offering: https://www.fourkitchens.com/blog/development/graphql-leveler-controlling-shape-query/ or https://github.com/APIs-guru/graphql-lodash

---

Do you think this could be implemented?

**Comment by smkhalsa** [comment]
> Is there a way to manipulate the graphql file so I end up with an object `profilePictureId.id`

No. Since ferry's data types are generated at compile-time, this would require significant changes to the generators.

Why don't you just add a new root-level query to your schema that returns the data you are interested in?

**Comment by ValentinVignal** [comment]
@smkhalsa The goal was to be able to reuse the end point already coded from my backend without implementing any changes in the graphQL schema.

But thank you for your quick answer anyway ! I guess you can close the issue if this is not in your roadmap.

**Comment by smkhalsa** [comment]
Ok, I'll close for now then.

I'd like to make the generators more extendable once the Dart static metaprogramming language features arrive.
