### ISSUE TITLE
 Disposing client 

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/ferry#242]
Disposing client, doesn't dispose the typedLinks initialized in the `Client`. The Client class doesn't override the dispose method. the dispose method in the super class is returning null.

Shouln't it be something like this in the `Client` class?

```
@override
Future<void> dispose() async {
    await _typedLink.dispose();
}
```
I'm not sure if there is any other mechanism that's taking care of this.

Also, Who is responsible to dispose the `Link` that we pass to the client(library or user)?

**Comment by smkhalsa** [comment]
Good catch. We should add dispose methods to the gql_typed_link and the client. if you want to open a PR, feel free.

In the meantime, you can simply pass your own link and dispose of it manually.

**Comment by smkhalsa** [comment]
quick update: 

I'm waiting for https://github.com/gql-dart/gql/pull/265 to be merged before fixing this.

**Comment by smkhalsa** [comment]
After giving this some more thought, I believe that every `TypedLink` (including the `Client` itself) should only dispose of resources that are created by that `TypedLink` itself. The life of a resource passed into a `TypedLink` might extend beyond the life of the `TypedLink`, so we should leave the responsibility of disposing of those resources to the user.

In the case of the `Client` `TypedLink`, the required `link` parameter should be disposed of by the user. In the case of `cache` and `requestController`, they should only be disposed of in the `Client.dispose()` method if they were created by the client (i.e. if nothing was provided by the user)
