### ISSUE TITLE
Build.yaml issue with VSCode and flutter

### ISSUE THREAD

**Issue by kinski76** [gql-dart/ferry#250]
Hi

When I create a build.yaml I get the following error

Property targets is not allowed.yaml-schema: JSON Schema for hammerkit's build file

This is using flutter and vs code. Any pointers please?

**Comment by smkhalsa** [comment]
please direct questions to the discord

**Comment by horgag** [comment]
Having the same issue. What's the discord channel?

**Comment by horgag** [comment]
any solution to this @kinski76 https://github.com/gql-dart/ferry/issues/250#issue-985104474

**Comment by smkhalsa** [comment]
https://discord.com/invite/tXTtBfC
