### ISSUE TITLE
Analyzer version

### ISSUE THREAD

**Issue by delCatta** [gql-dart/ferry#282]
I'm trying to use this package with the auto_route but I'm having version issues:

```
Because ferry_generator >=0.4.3 <0.5.0-dev.0 depends on gql_code_builder ^0.2.0 which depends on analyzer ^1.2.0, ferry_generator >=0.4.3 <0.5.0-dev.0 requires analyzer ^1.2.0.
And because auto_route_generator >=2.4.0 depends on analyzer ^2.3.0, ferry_generator >=0.4.3 <0.5.0-dev.0 is incompatible with auto_route_generator >=2.4.0.
```

**Comment by smkhalsa** [comment]
You should be able to get around this by setting a dependency_override on analyzer to 2.3.

I'm not sure we should update our dependency because we'd create this same issue for anyone who is not using analyzer >2.0 yet.

**Comment by delCatta** [comment]
> You should be able to get around this by setting a dependency_override on analyzer to 2.3.
> 
> I'm not sure we should update our dependency because we'd create this same issue for anyone who is not using analyzer >2.0 in any of their dependencies.

Awesome! Done it by adding on my `pubspec.yaml` file:
```
dependency_overrides: 
  analyzer: ^2.3.0
```
Closing this now.

**Comment by britannio** [comment]
> You should be able to get around this by setting a dependency_override on analyzer to 2.3.
> 
> I'm not sure we should update our dependency because we'd create this same issue for anyone who is not using analyzer >2.0 in any of their dependencies.


@smkhalsa I think that the correct resolution to this is to update the dependency constraint on the analyzer package.

If the breaking changes introduced in `analyzer 2.0.0` do not break Ferry's usage of `analyzer` then the constraint can be updated to `analyzer: >=1.7.2 <3.0.0`. 


Applying this change will remove the need for a dependency override on `analyzer` which can cause unexpected issues, and it won't "create this same issue for anyone who is not using analyzer >2.0 in any of their dependencies"

**Comment by smkhalsa** [comment]
@britannio sounds good to me.

**Comment by momrak** [comment]
@smkhalsa If I was to create a PR here, would just adding the constraints and running the tests OK be enough, or what does analyzer actually do? 

Is it only used for static analysis when formatting? And in that case could it be moved to a dev_dependency, or am I missing something?

**Comment by smkhalsa** [comment]
`ferry_generator` has a direct dependency on `analyzer`. Also, `analyzer` is a transitive dependency via `gql_code_builder`, so it will need to be upgraded there first.
