### ISSUE TITLE
Documentation mistype - custom scalar

### ISSUE THREAD

**Issue by deandreamatias** [gql-dart/ferry#285]
In [ferry docuemntation](https://ferrygraphql.com/docs/custom-scalars/#complete-buildyaml-example), can see a complete build.yaml example.
This build.yaml has a misstype with `type_overrides` that should be `types_overrides`. Attention with extra s in types.

With mistype `type_overrides`, I get [this error](https://stackoverflow.com/questions/68056425/flutter-ferry-custom-scalar-serializer-has-non-dynamic-type) but with `types_overrides` no

**Comment by smkhalsa** [comment]
> With mistype type_overrides, I get this error but with types_overrides no

No, this is not a typo. It should be `type_overrides`.

Just because the error isn't thrown when you change it to `types_overrides` doesn't mean that your type overrides are in fact being recognized (feel free to test it). You could put any key, it will just be ignored by the builder.

**Comment by deandreamatias** [comment]
Interesting. So, I back to first problem described [here](https://stackoverflow.com/questions/68056425/flutter-ferry-custom-scalar-serializer-has-non-dynamic-type).
Should I close this issue and open other with these problem?

**Comment by smkhalsa** [comment]
I suggest using the discord to get support with your specific implementation
