### ISSUE TITLE
How are GraphQL operations stored in a file into a Flutter app managed by Ferry?

### ISSUE THREAD

**Issue by warcayac** [gql-dart/ferry#286]
When a query is run on the interactive GraphQL interface, an entry is generated in its log, for example:
```
mygraphql | 2021-09-29T17:22:14.196819135Z 0 error(s) as anonymous in 38.28ms :: mutation PurchaserExists($p1: String!, $p2: String!, $p3: String!, $p4: Int!, $p5: String!, $p6: String!, $p7: Int!, $p8: Int!, $p9: String!) { registerPurchaser( input: {email: $p1, password: $p2, fullName: $p3, iddocType: $p4, iddocNo: $p5, phoneNo: $p6, customerType: $p7, district: $p8, address: $p9} ) { result { uid } } }
```
So I understand an entry is an operation executed in Postgraphile.

In my Flutter app I have 2 (*.graphql) files, one for queries and another for mutations, then making any request to server from my app (by using Ferry), in the Postgraphile's log an entry is generated, but this entry contains all operations stored in the file where the request was originated. 

Example: In `fileA.graphql` contains 10 queries (query1,query2,...), then the entry generated by Postgraphile is some like this:

```
mygraphql | 2021-09-29T16:56:08.372551771Z 0 error(s) as anonymous in 4.79ms :: query1 {} query2 {} ... query10 {} 
```
How should I interpret it? Are all queries into that file run when calling a only query? Should I create a file per GraphQL operation?

**Comment by smkhalsa** [comment]
Similar to your previous issue, it sounds like this is a question about Postgraphile.

With ferry, you can organize your queries and mutations however you wish, whether that's in one file or many.

Please use the github issue tracker for bug reporting and feature requests. If you'd like to ask questions about your integration or other tooling in the graphql ecosystem, please use the Discord channel.
