### ISSUE TITLE
GraphQL Errors and Forward

### ISSUE THREAD

**Issue by tiennano** [gql-dart/ferry#290]
I have a GraphQL Errors and Forward issue.
Inside all graphql query is using token to authentication with server, but sometimes this token expires resulting in response error. I want to catch this event graphql error so that call API refresh token then forward graphql API error.
Please help me if you have any solution. Thanks!

**Comment by smkhalsa** [comment]
You can create your own custom link to handle errors in whatever way you wish. I suggest using the discord to get help, as the github issue tracker is used for bug reporting and feature requests.
