### ISSUE TITLE
Multiple mutations (transaction) rollback not working on error

### ISSUE THREAD

**Issue by HakimKramdi** [gql-dart/ferry#292]
Hello,

I used Ferry with Hasura (Postgres) in a Flutter project, I generated the client following the documentation and everything is ok, I managed to fetch and update data.

I have a table user and table passions and a many to many relation between them ( a user can have multiple passions and passions can be linked to multiple users) 

Hasura clearly sates in their documentation "If multiple mutations are part of the same request, they are executed sequentially in a single transaction. If any of the mutations fail, all the executed mutations will be rolled back."
[hasura documentation](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/multiple-mutations.html)

Which I verified with a query like this:
`mutation EditUserWithPassions(
  $_user_input: user_set_input!
  $_id: Int!
  $passions: [userPassion_insert_input!]!
) {
  update_user(where: { id: { _eq: $_id } }, _set: $_user_input) {
    affected_rows
  }
  delete_userPassion(where: { userId: { _eq: $_id } }) {
    affected_rows
  }
  insert_userPassion(
    objects: $passions
    on_conflict: { constraint: userPassion_pkey }
  ) {
    affected_rows
  }
}`

Using Hasura query api, when I provide a faulty data in $passions, this query is totally rolledback.

When I use the client generated with Ferry on my flutter project I try the same thing this using this code:
`     
 final updateUserWithPassionsQuery = GEditUserWithPassionsReq((b) => b
        ..vars.G_user_input.name = "new Name"
        ..vars.G_user_input.countryIso = "FR"

        ..vars.G_user_input.birthDate.value = "2000-11-11"
        ..vars.G_user_input.gender = "gender_male"
        ..vars.G_user_input.userId = "user_id_1"
        ..vars.G_id = 25
        ..vars.passions.addAll([
          GuserPassion_insert_input((h) => h
            ..passionId = 1
            ..userId = 25),
          GuserPassion_insert_input((h) => h
            ..passionId = 100
            ..userId = 25)
        ]));`

If there is and error like here the passionId = 100 does not exists  in my database, the query return an error but still partially works ( the user is updated with the new name ... ) 

So my question is: Are transactions supported for multiple mutations in one query  ? 

My flutter doctor here:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!`

I can provide more information if necessary.
Thank you in advance for your help.

**Comment by smkhalsa** [comment]
> Are transactions supported for multiple mutations in one query ?

no

**Comment by smkhalsa** [comment]
If someone wants to take this on, I'm open to PRs, but this isn't something I intend to work on in the foreseeable future.
