### ISSUE TITLE
How to handle cache invalidation when the authentication changes?

### ISSUE THREAD

**Issue by elertan** [gql-dart/ferry#293]
My GraphQL API exposes a graph named `me` within the query root which retrieves data that is based on the current authenticated user, such as account details. Considering this query does not take in any variables and simply uses the Authorization header to authenticate the user I figured that ferry would not automatically be able to refresh the data associated with the `me` graph, and therefore me having to evict the potentially cached results of a previously logged in user.

In my current implementation I build a link with the authorization header based on the current application state, when a user logs in or out I rebuild the client updating the link to include/exclude the header where necessary.
After doing so I clear the cache using `cache.clear()` and perform a garbage collection using `cache.gc()`.

This results in the ferry pushing a new `OperationResponse` to the listeners of this query, with the data set to `null`. When trying to perform the same query again it simply keeps returning `null` as the new cached value for the same given query.

I have also tried to create a custom `HttpLink` that injects the header automatically where necessary as I considered the fact that maybe rebuilding the client would cause the listeners of the query that was created with the previous client to not be notified of any new operation responses, but that did not matter as far as I could tell.

How come that the `OperationResponse`'s data keeps returning `null` from cached results? I have even tried to use `CacheAndNetwork` to enforce the use of the network which still only comes back with `null`. I am certain that it does not have to do with the API, as simply restarting the application where the link is set correctly during initialization does come back with the right results again.

Thanks for the help, and the awesome library!

**Comment by smkhalsa** [comment]
> when a user logs in or out I rebuild the client updating the link to include/exclude the header where necessary.

You probably shouldn't rebuild the entire client. You really only need to clear the cache (or possibly just evict the key for "me")



> I have also tried to create a custom `HttpLink` that injects the header automatically where necessary as I considered the fact that maybe rebuilding the client would cause the listeners of the query that was created with the previous client to not be notified of any new operation responses

This seems like the correct approach. Listeners are based on the instance of the TypedLink (i.e. Client).

Are you adding the new request to Client.requestController? Ferry does this automatically when you first start listening to a query, but any subsequent requests need to be added manually. 

Are you getting any exceptions? Also, what is the "DataSource" of the new response after you've cleared the cache.

**Comment by smkhalsa** [comment]
closing since I haven't heard back

**Comment by elertan** [comment]
My apologies @smkhalsa .
I haven't been working on the project and forgot to respond to your comment afterwards.
I appreciate the quick and insightful comment you have given me, I'll come back and re-open the issue if I am still facing the issue later.

Many thanks!
