### ISSUE TITLE
proxy.writeQuery - doesn't write

### ISSUE THREAD

**Issue by awaik** [gql-dart/ferry#30]
## Description

The bug appears when I trying to update the cache in the example app.
The results are printed in the code, when we use `deleteTodoMutationHandler` 
https://github.com/awaik/todo_ferry_example/blob/master/lib/src/client.dart

## The code
```
    print('resMap --- ${resMap}');
    proxy.writeQuery(query, resMap);
    print('proxy.readQuery(query) --- ${proxy.readQuery(query)}');
```
`proxy.readQuery(query);` returns the old, not updated value.

So, the line `proxy.writeQuery(query, SomeMap);` doesn't change the cache.

**Comment by DoctorJohn** [comment]
I tracked down a bug which might be the underlying issue of this problem. I'll report it later today along with an PR to fix it.

**Comment by DoctorJohn** [comment]
This is possibly related to #39. I first tought myself `Cache.writeQuery` would not work because `Cache.readQuery` did not return what has just been written to the cache. But it turned out `Cache.readQuery` did just not return the cached data because of the #39.
