### ISSUE TITLE
Method request isn't defined for the class 'Future<Client>'

### ISSUE THREAD

**Issue by true2thepen** [gql-dart/ferry#301]
Hello,

In following the docs to create a pure dart (no Flutter) app I get the following:

Error: The method 'request' isn't defined for the class 'Future<Client>'.
 - 'Future' is from 'dart:async'.
 - 'Client' is from 'package:ferry/ferry.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/ferry-0.10.4/lib/ferry.dart').
Try correcting the name to the name of an existing method, or defining a method named 'request'.

**Comment by smkhalsa** [comment]
Without seeing your code, it seems that you are trying to call `request` on an async function that is returning a client, not on the client itself.

Please use the discord for general assistance using ferry.

**Comment by true2thepen** [comment]
Attached as a zipfile the whole dart project. 
The Future code is commented out. Then it works. Once you switch the non-async version for the async version in lib/countries_client.dart it gives the error. 
[countries_client.zip](https://github.com/gql-dart/ferry/files/7513706/countries_client.zip)

**Comment by smkhalsa** [comment]
Closing this since really a request for assistance with Dart programming, not an issue with Ferry. 

Feel free to use the discord to ask for assistance.

**Comment by true2thepen** [comment]
For those running into this, the solution is to make your main function async and change the examples line:
final client = Client( link: link, cache: cache, );
to 
final client = await Client( link: link, cache: cache, );

Though the solution has been found, the company has decided to go with another solution.

Attached is a working example.
[countries_client_fixed.zip](https://github.com/gql-dart/ferry/files/7516199/countries_client_fixed.zip)
