### ISSUE TITLE
Subscriptions not working 

### ISSUE THREAD

**Issue by Sameerkash** [gql-dart/ferry#305]
1. There are no docs for subscriptions, this would be really helpful. Or I am not sure if ferry does not support subscriptions.

2. Because I 've been trying to make them work without any success. 

```
final messageSubScripton = GPollMessagesReq();

      Operation(
              client: client,
              operationRequest: messageSubScripton,
              builder: (context,
                  OperationResponse<GPollMessagesData, GPollMessagesVars>?
                      response,
                  object) {
                  ...
                  }
 ```                 
 
 I am trying the same syntax as query but unable to listen to any changes, the observer doesn't even trigger

**Comment by smkhalsa** [comment]
What `gql_link` are you using? Subscriptions should work out of the box if you are using a compatible link.

**Comment by Sameerkash** [comment]
@smkhalsa by `gql_link`, do you mean the server link? I am running a apollo server locally

**Comment by smkhalsa** [comment]
No, I mean the link from the `gql_link` (e.g. `HttpLink`) that you pass to the Client when instantiating it.

**Comment by atik7** [comment]
I don't know if this related, but following code works for me,

`final wsLink = WebSocketLink(
    null,
    autoReconnect: true,
    reconnectInterval: Duration(seconds: 5),
    channelGenerator: () => WebSocketChannel.connect(
        Uri.parse(url),
        protocols: ['graphql-ws']),
  );`

**Comment by Sameerkash** [comment]
@smkhalsa 

This is how my client looks 
```

final link = HttpLink("http://192.168.29.223:4000/graphql");

final client = Client(link: link);

```

@atik7 

could you give me a bit more context on how you are instantiating the client? with that link?

**Comment by smkhalsa** [comment]
HttpLink won't work for subscriptions. You'll need something like WebSocketLink as described by @atik7.

I recommend using the discord for general support. 

I'm closing this issue since there doesn't appear to be any bug or feature request.

**Comment by Sameerkash** [comment]
Thanks @smkhalsa
