### ISSUE TITLE
Fresh responses from the same initialised client

### ISSUE THREAD

**Issue by qbait** [gql-dart/ferry#311]
I'm initializing my client when the app starts

```
final link = HttpLink("[path/to/endpoint]");
return Client(link: link);
```

later I'm re-using that client everywhere in my app. However, I've noticed that when I:
1) execute the query `client.request(queryReq).listen((response) => print(response));`
2) execute the mutation that mutate data that I'm quering `client.request(mutationReq).listen((response) => print(response));`
3) execute the query `client.request(queryReq).listen((response) => print(response));` again
I'm getting the old data.

Only after reinitializing the client, I will get the fresh data. Can I somehow force the client to give me the fresh data without reinitializing it?

**Comment by smkhalsa** [comment]
Even if your graphql server will only return a single response, the application may receive additional data (e.g. when the cache updates as a result of another request that alters the same data).

In any case, you can always turn the stream into a future using the `first` property.

**Comment by qbait** [comment]
@smkhalsa That doesn't answer my question why data aren't refreshed correctly with the same client.
I reckon you wrote an answer to my other question about the Future here? :0

**Comment by smkhalsa** [comment]
Ah, yes. I’m on my phone 😂.

As to this question, the default FetchPolicy is CacheFirst for queries, so it sounds like you’re getting the cached results the second time. 

You might want to try using the NetworkOnly policy.

**Comment by smkhalsa** [comment]
Also, I recommend using the discord for assistance with using the library. 

We use GitHub exclusively for bug reports and feature requests.
