### ISSUE TITLE
Problems running build_runner.

### ISSUE THREAD

**Issue by diogoorcelli** [gql-dart/ferry#316]
**I'm having a lot of trouble running build_runner. Always get the following messages.** 

[SEVERE] built_value_generator:built_value on lib/__generated__/schema.schema.gql.dart:
Error in BuiltValueGenerator for abstract class GUserUpdateManyMutationInput implements Built<GUserUpdateManyMutationInput, dynamic>.
Please make the following changes to use BuiltValue:

1. Make field appleId have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
2. Make field createdAt have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
3. Make field email have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
4. Make field facebookId have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
5. Make field googleId have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
6. Make field name have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
7. Make field photo have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
8. Make field pin have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
9. Make field pinTries have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
10. Make field token have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
11. Make field updatedAt have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
[SEVERE] built_value_generator:built_value on lib/__generated__/schema.schema.gql.dart:
Error in BuiltValueGenerator for abstract class GUserUpdateManyWithWhereWithoutFavoritedProductsInput implements Built<GUserUpdateManyWithWhereWithoutFavoritedProductsInput, dynamic>.

**My build.yaml:**

targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: graphql_app|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: graphql_app|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: graphql_app|lib/schema.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: graphql_app|lib/schema.graphql

**pubspec.ymal**

dependencies:
  flutter:
    sdk: flutter
  ferry: any
  gql_http_link: any
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  ferry_generator: any
  build_runner: any
  gql_build:
  gql_code_builder:

dependency_overrides:
  gql:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: master
      path: gql/
  gql_build:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: master
      path: codegen/gql_build/
  gql_code_builder:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: master
      path: codegen/gql_code_builder/
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

**Does anyone know why these errors happen?**

**Comment by axrs** [comment]
I get the similar issues on Windows, (but not on my MacOS or Linux machines), using the same codebase and versions of Dart.

**Comment by axrs** [comment]
@diogoorcelli 

If you're running Windows, and it may not be related, by my non-dynamic type errors were the result of invalid path separators. This was a the fix for me: https://github.com/gql-dart/ferry/issues/298#issuecomment-1009613691
