### ISSUE TITLE
Ferry Incompatible with Flutter 2.8.1

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/ferry#320]
Due to the minimum requirement of analyzer 3.0.0 from flutter v2.8.1, ferry_generator uses analyzer v1.7.2 and needs to be upgraded to v3.0.0. 

Although the build runs with a warning currently. The build fails with errors related to gql_code_builder.

**Comment by mikedigit** [comment]
@smkhalsa @knaeckeKami  Any way you can look at this issue ? This actually completely brokes code generation on my end, and even if I generate code in another project,  I can't use default_scalar_serializer since it depends on gql_code_builder.

**Comment by mikedigit** [comment]
I was working on a solution similar to this, and was planning to share it here.
Thanks for helping by providing a specific analyzer version.
And yes even tho it works I can't say that this is ideal, and hope you can work something out soon.

A good starting would be to simply update the pubspec documentation to point people toward this temporary fix.

**Comment by knaeckeKami** [comment]
Yeah, I'll see if I can make a PR for gql_code_builder soon.

**Comment by NettSite** [comment]
I am pretty sure this is related, but as I am no expert at this, I could very easily be wrong.

While building, I spotted a message:

`Please update to the latest 'analyzer' version (3.2.0) by running 'flutter packages upgrade'.`

The build failed as follows:
```
[SEVERE] built_value_generator:built_value on lib/graphql/authentication/forgotpassword/forgotpassword.req.gql.dart:
Error in BuiltValueGenerator for abstract class GxxxReq implements Built<GxxxReq, dynamic>, OperationRequest<dynamic, GxxxVars>.
Please make the following changes to use BuiltValue:

1. Make field optimisticResponse have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```
An attempt to upgrade analyzer to 3.2.0 fails:
```
Because ferry_generator >=0.4.3 <0.5.0-dev.0 depends on gql_code_builder ^0.2.0 which depends on analyzer ^1.2.0, ferry_generator >=0.4.3 <0.5.0-dev.0 requires analyzer ^1.2.0.
So, because xxx depends on both analyzer ^3.2.0 and ferry_generator ^0.4.4, version solving failed.
```

I tried using the dependency override mentioned above with no luck.

**Comment by knaeckeKami** [comment]
Maybe, but this can also happen because of other issues, like using queries that have no name or using the same query name twice, or typos in queries. Be sure to check for that.

I think I'll be able to look into upgrading the analyzer version this weekend

**Comment by NettSite** [comment]
> Maybe, but this can also happen because of other issues, like using queries that have no name or using the same query name twice, or typos in queries. Be sure to check for that.
> 
Thanks! I had used the name of a mutation in the incorrect case. 

I would probably never have noticed it without your help.

**Comment by knaeckeKami** [comment]
opened a PR @  https://github.com/gql-dart/gql/pull/298 , after that ferry_generator has to be updated as well

**Comment by mikedigit** [comment]
@knaeckeKami your pr has been merged, could you now update the ferry_generator package?

**Comment by fabiancrx** [comment]
Is there any updated fork to use in the meantime?

**Comment by knaeckeKami** [comment]
@agent3bood said he would take care of ferry_generator. But if he does not have the time I might do it on the weekend

**Comment by agent3bood** [comment]
I have a working app with the following versions, 

`pubspec.lock`
```
  ferry_generator:
    dependency: "direct dev"
    description:
      name: ferry_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.4"
```

`pubspec.yaml`
```
dependency_overrides:
  built_collection: ^5.1.1
  analyzer: ^3.3.1
  gql_exec: ^0.4.0
  rxdart: ^0.27.3
```

**Comment by mikedigit** [comment]
@agent3bood @knaeckeKami  any update on the ferry_generator part ?

**Comment by agent3bood** [comment]
@mikedigit 
The above configurations are working without issue, are you having any problems with it?

**Comment by mikedigit** [comment]
No sorry just wondering, when all dependencies will work out of the box, without needing to override dependencies that is all.
I am currently working with dev version of ^0.5.0-dev.10 and ferry ^0.10.5-dev.3 to make sure i'm up to date.
But i would love to be able to migrate to "stable" versions

**Comment by appinteractive** [comment]
any updates? For me its still broken, also with the overwrites mentioned here.

I get:
```
flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 655ms

[INFO] Precompiling build script......
[WARNING] /opt/homebrew/Caskroom/flutter/2.10.3/flutter/.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.2.0/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('/opt/homebrew/Caskroom/flutter/2.10.3/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 886ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

last week it did still work, but I needed to remove test and integration_test packages to be able to run `flutter pub get`

**Comment by 2shrestha22** [comment]
Use prerelease builds that should work fine. 
```yaml
dependencies:
    ferry: ^0.10.5-dev.3

dev_dependencies:
  ferry_generator: ^0.6.0-dev.1
```

**Comment by knaeckeKami** [comment]
just published new versions which should fix this.
