### ISSUE TITLE
How do i perform a pollingInterval for query?

### ISSUE THREAD

**Issue by tc** [gql-dart/ferry#327]
In apollo, i can provide an attribute `pollingInterval: 500` to poll a query every 500 ms, how can I do this with ferry?

**Comment by smkhalsa** [comment]
You should be able to do this with a custom gql_link

**Comment by tc** [comment]
thanks, is there a tutorial how to do this with a custom gql_link?

**Comment by smkhalsa** [comment]
Not that I'm aware of. I'd poke around the gql_link repo to look for examples. The Link interface is pretty simple.

**Comment by tc** [comment]
alternatively, does ferry support `Subscription`?

**Comment by rneswold** [comment]
@tc: yes, it supports subscriptions. You can close this issue if that solves your problem.
