### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by SanjiKir** [gql-dart/ferry#33]
Hey man! Thanks for working on this project! I just have 1 quick question out of curiosity and due to some problems I meet every day in other graphql package. 

What is your motivation and how do you see the future of this project? 
And also, why did you decide to build this package instead of contributing to the original package?

Thanks for your answers, sorry for creating an issue,  IDK where else can I ping you. 
Cheers!

**Comment by klavs** [comment]
Hey @SanjiKir! I'm the author of most of the packages in `gql-dart/gql` repo.

I just want to let you know that `gql_link`, on which `ferry` is based, is already used by Artemis and there are open issues discussing the outsourcing of the `graphql_flutter` Link layer to `gql_link`. Which means `ferry` can focus on the caching aspect of a client and a broader community of users work on the Link aspect.

I am considering contributing to `ferry` when the Link layer is more stable.

`gql-dart` is very much about promoting community involvement and accepting contributions which are in line with the project goals and direction.

**Comment by smkhalsa** [comment]
Hi @SanjiKir, author of `ferry` here.

I made a few contributions to `graphql` / `graphql_flutter`, but there were some architectural decisions that didn't suit my needs. To name a few:

1. Coupling of Cache and Store, making it difficult to implement custom stores (such as `hive_store`)
1. Implementation of client logic within the `graphql_flutter` package, making it difficult to interact with the client outside of flutter
1. [Lack of AST-based cache normalization](https://github.com/zino-app/graphql-flutter/issues/471)
1. Lack of Type integration (e.g. typed readQuery / writeQuery methods on the cache)
1. Embedded cache update logic within query definitions, making it impossible to serialize for offline mutations

I've tried to keep the library as modular as possible and lean on the excellent work @klavs has done with the `gql` packages. The current `ferry` architecture consists of:

1. [gql_link](https://pub.dev/packages/gql_link) package for networking
1. [normalize](https://pub.dev/packages/normalize) package for normalization / normalization of GraphQL responses
1. [gql_build](https://pub.dev/packages/gql_build) package for type generation
1. Cache (bundled in `ferry` package) for reading and writing GraphQL Queries and Fragments
1. Store (bundled in `ferry` package) for data storage
1. Client (bundled in `ferry` package) for routing queries
1. Flutter Widgets (bundled in `ferry` package) as simple wrappers around `Client.responseStream`

Also, leaning heavily on Dart Streams (with help from [rxdart](https://pub.dev/packages/rxdart)) has allowed us to keep the core Client logic fairly simple yet powerful.

I'm using `ferry` on personal projects and intend to continue to develop the library as time permits. My roadmap right now includes:

1. more robust generated data classes
1. documentation
1. tests and examples
1. offline mutations
