### ISSUE TITLE
Error when run the command "dart/bin/countries_client.dart

### ISSUE THREAD

**Issue by pavannx** [gql-dart/ferry#331]
import 'dart:ui' show ImageFilter;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/colors.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show Color, Brightness;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/context_menu.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/dialog.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/route.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble, ImageFilter;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/slider.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/switch.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/text_field.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show BoxHeightStyle, BoxWidthStyle;
       ^
/users/matheus.pavan/sdk/flutter/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;

**Comment by smkhalsa** [comment]
Closing as this appears unrelated to ferry
