### ISSUE TITLE
Build runner generation on Flutter 2.10.3 for schema.graphql failed!!

### ISSUE THREAD

**Issue by minhhoangtn** [gql-dart/ferry#348]
I can not generate code from schema.graphql file because `flutter pub run build_runner build --delete-conflicting-outputs`
 failed.

build_runner result:
`[INFO] Generating build script...
[INFO] Generating build script completed, took 378ms

[INFO] Precompiling build script......
[WARNING] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.2.0/lib/src/ast.dart:618:12: Error: A non-null value must be returned since th
e return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs
/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 5.5s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78
`

build.yaml :
`targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: untitled|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: untitled|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: untitled|lib/schema.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: untitled|lib/schema.graphql`

pubspec.yaml: 
`dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ferry: ^0.10.4
  gql_http_link: ^0.4.0
  gql_code_builder:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  ferry_generator: ^0.4.4`

**Comment by MubeenNaeem** [comment]
Are you able to resolve it?

**Comment by MubeenNaeem** [comment]
@minhhoangtn 
[WARNING] Configuring `gql_build:schema_builder` in target `app:app` but this is not a known Builder

Are you familiar of this error?

**Comment by minhhoangtn** [comment]
> @minhhoangtn 
> 
> [WARNING] Configuring `gql_build:schema_builder` in target `app:app` but this is not a known Builder
> 
> 
> 
> Are you familiar of this error?

Maybe you are missing ferry_generator in your dev_dependencies

**Comment by appinteractive** [comment]
When using the ferry_generator fork, nothing gets generated, and everything that was there, gets deleted:

<img width="481" alt="grafik" src="https://user-images.githubusercontent.com/432828/165392969-c324a695-2944-4134-a4e3-2a3e9f0fb1af.png">

**Comment by appinteractive** [comment]
So I can finaly confirm that the isue is gone with using all stable versions and pinning the versions:

```yaml
ependency_overrides:
  analyzer: ^3.3.0
  gql: 0.13.0
  ```

At least as long I do NOT use `--delete-conflicting-outputs`

**Comment by sunderee** [comment]
I'm having the same issue. With the stable versions of `ferry` and `ferry_generator`, I'm getting

```
[WARNING] ../../../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.2.0/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('../../../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 5.9s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

After upgrading both packages to dev, I'm getting this:

```
[WARNING] Configuring `gql_build:schema_builder` in target `shsdk:shsdk` but this is not a known Builder
[WARNING] Configuring `gql_build:ast_builder` in target `shsdk:shsdk` but this is not a known Builder
[WARNING] Configuring `gql_build:data_builder` in target `shsdk:shsdk` but this is not a known Builder
[WARNING] Configuring `gql_build:var_builder` in target `shsdk:shsdk` but this is not a known Builder
[WARNING] Configuring `gql_build:serializer_builder` in target `shsdk:shsdk` but this is not a known Builder
[WARNING] Configuring `ferry_generator:req_builder` in target `shsdk:shsdk` but this is not a known Builder
[SEVERE] Nothing can be built, yet a build was requested.
```

It doesn't matter whether or not I use the `--delete-conflicting-outputs` flag.

**Comment by appinteractive** [comment]
@sunderee did you add gql_build as a package?

**Comment by sunderee** [comment]
@appinteractive correct, I did. To no avail. I've dropped working with the library and I've instead reverted to manually deserializing all models.

**Comment by chungonion** [comment]
> @appinteractive correct, I did. To no avail. I've dropped working with the library and I've instead reverted to manually deserializing all models.

if you are working with dev version check [this](https://github.com/gql-dart/ferry/issues/326)

**Comment by knaeckeKami** [comment]
Fixed with the latest stable
