### ISSUE TITLE
when are you planning to update on pub.dev

### ISSUE THREAD

**Issue by Suryapratap-R** [gql-dart/ferry#355]
its been 10 months since the last update.

**Comment by ebsangam** [comment]
12 months

**Comment by 2shrestha22** [comment]
There are pre-release builds you can use that.

**Comment by knaeckeKami** [comment]
I am planning a new public release soon.

There is still a blocker, I don't have access to the ferry_exec package which is still owned by @smkhalsa, so I can't publish updates for it. 

Once this is resolved, I'll publish new stable releases soon.

In the worst case I'll have to fork ferry_exec and publish it under a new name temporarily, but I really would like to avoid that.

**Comment by knaeckeKami** [comment]
Published.
