### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by etegan** [gql-dart/ferry#356]
Last release was 10 months ago which is starting to cause issues with dependencies. I just want to know if this repo is still active?

**Comment by smkhalsa** [comment]
Hi there. I haven't had much time to work on Ferry in a while, and I'm not sure I will in the near future.

If anyone is interested in contributing, I'd be happy to support them.

**Comment by etegan** [comment]
Appreciate the transparency. Maybe add a disclaimer to the top of the README so people know that the package will probably not see any updates in the near future.

**Comment by chungonion** [comment]
hi @smkhalsa . Firstly really appreciate your work and efforts poured into this package, and I just love to use this package to generate the needed graphql classes. 

May I ask two things here ...
1) Is the preview version ready for release? I am using that version (due to dependency issue),  and I don't face any particular issue there right now..
2) Can all transitive dependencies be updated first? even if no new features are expected ? 

Thank you!

**Comment by chungonion** [comment]
> Hello, Anyone with a working fork?. The example code does not seem to work as well.

I don't know whether there is a fork or not. Using the dev version seems fine to me 

Not sure whether [this](https://github.com/gql-dart/ferry/issues/326) is helpful to you or not

**Comment by nyelnizy** [comment]
@chungonion 
I checked the link you sent and I keep get this error, with both the example app and mine: 
Make field vars have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.

**Comment by nyelnizy** [comment]
@chungonion 
I got it working...
I followed the link and changed the ferry_generator dev dependency to this..
ferry_generator:
    git: #Try and not use a fork
      url: https://github.com/axrs/ferry.git
      path: packages/ferry_generator

It works now, thanks once again.

**Comment by ValentinVignal** [comment]
Hello @smkhalsa I'm willing to spend some time helping maintaining the repo, but I would need some guidance

**Comment by smkhalsa** [comment]
Awesome 😎. I'm happy to support. Let me know what you need.

**Comment by ValentinVignal** [comment]
Thanks @smkhalsa I guess some information on where to look for to know what is the roadmap, priorities etc.
Some _"easy"_ issues/features that are actionnable to get to know the repo
And I haven't search for it yet, but I guess there is a _"how to contribute"_ guide somewhere

**Comment by ebsangam** [comment]
Lets give first priority to `analyzer` update. We are not able to use some package due to dependency issues.

**Comment by knaeckeKami** [comment]
I would also be willing to do some maintenance work. I use gql/ferry in production and would like to keep dependencies up to date and triage some PRs. 

I understand that you don't have much time to spend on your repositories @smkhalsa @klavs , are you willing to give volunteers to write or maintain access to help keep ferry/gql alive?

**Comment by klavs** [comment]
@knaeckeKami please check Discord.

**Comment by 2shrestha22** [comment]
Yes it is active I think.

**Comment by knaeckeKami** [comment]
I also think so ;)

**Comment by knaeckeKami** [comment]
Just published a new version of ferry.
