### ISSUE TITLE
update ferry_flutter dependency

### ISSUE THREAD

**Issue by Gustav0ar** [gql-dart/ferry#37]
I'm getting this error while trying to use latest ferry (0.4.0) with ferry_flutter:

```
ferry_flutter ^0.1.0 which depends on ferry ^0.3.1+2, ferry ^0.3.1+2 is required.
So, because test_project depends on ferry ^0.4.0, version solving failed.
```

Also, it causes conflicts while running the usage provided [here](https://github.com/gql-dart/ferry/tree/master/ferry), since objects and functions are declared in multiple libraries

**Comment by smkhalsa** [comment]
Should be fixed in https://github.com/gql-dart/ferry/pull/36. I just published a hotfix with this PR. Let me know if you still have any issues.

**Comment by Gustav0ar** [comment]
Yeahp, it's fixed, thanks

**Comment by alexandrim0** [comment]
Hello!

It looks like ferry_flutter is locked on not latest version of ferry.
Please, can you update dependency?

Thank you!
