### ISSUE TITLE
How to use retry for use refresh token?

### ISSUE THREAD

**Issue by ShourovRoy** [gql-dart/ferry#370]
How to use retry for use refresh token? please give a example

**Comment by knaeckeKami** [comment]
You need  a link that handles token refresh. See here: https://github.com/gql-dart/gql/blob/master/examples/gql_example_http_auth_link/lib/http_auth_link.dart

**Comment by chungonion** [comment]
I personally use [fresh_graphql](https://pub.dev/packages/fresh_graphql), and add that as an link
