### ISSUE TITLE
Ferry generator 0.6.0 incompatible with Ferry 0.10.4? 

### ISSUE THREAD

**Issue by MansOlm** [gql-dart/ferry#379]
I am trying to install the latest versions of Ferry and Ferry generator in a new dart project but I am getting the following error: 

> [ferry_test] dart pub get
> Resolving dependencies...
> Because ferry_generator >=0.6.0 depends on gql ^0.14.0 and ferry >=0.10.3 <0.11.0-dev.0 depends on gql ^0.13.0, ferry_generator >=0.6.0 is incompatible with ferry >=0.10.3 <0.11.0-dev.0.
> So, because ferry_test depends on both ferry ^0.10.4 and ferry_generator ^0.6.0, version solving failed.
> exit code 1

Noticed that the Ferry generator version is verry new so I will use the 0.4.4 for now.

**Comment by knaeckeKami** [comment]
yes, I released ferry 0.10.5 which was compatible with it but withdrew it again because of some bad bug (see other issues here). 
I'll fix this bug shortly and release a new version.
