### ISSUE TITLE
Fragment Bug

### ISSUE THREAD

**Issue by parisholley** [gql-dart/ferry#38]
Didn't test to see if it only happens when nesting fragments or not, but if you have have a nested graph with ONLY a fragment, when normalized, it gets nulled...

```
foobar{
...fragment
}
```

i can work around by always asking for a typename

```
foobar{
__typename,
...fragment
}
```

**Comment by iscriptology** [comment]
You have an option to auto include __typename, can’t remember its name right now, see the source code.

**Comment by smkhalsa** [comment]
@parisholley I think this should be fixed with #41. Can you check and report back if not?

**Comment by smkhalsa** [comment]
closing this issue for now. Please let me know if you're still having an issue.
