### ISSUE TITLE
InputBuilder always generate setters with nullable parameter.

### ISSUE THREAD

**Issue by 2shrestha22** [gql-dart/ferry#386]
Generated code: 
![image](https://user-images.githubusercontent.com/24835256/186137117-035d42fc-77ff-4c71-a8cf-3831d093c78e.png)

Schema:
![image](https://user-images.githubusercontent.com/24835256/186137271-6a412374-22c4-43bb-aa1d-c26df377f459.png)

MutationReq: 
![image](https://user-images.githubusercontent.com/24835256/186137662-949cb830-76f2-4a54-b583-241c3e5a86cf.png)

Receipt field is non null in schema but it always generated nullable setter in InuptBuilder. Is this normal or can be fixed?

**Comment by knaeckeKami** [comment]
yes, that's normal.
see https://github.com/google/built_value.dart/issues/1038#issuecomment-849481054
