### ISSUE TITLE
bad generation result: conflict of identifier "update"

### ISSUE THREAD

**Issue by kerosan** [gql-dart/ferry#395]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/10149363/187671649-f80c524c-4961-4692-93f3-116b422ad0b1.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/10149363/187671760-ec371f11-aeb9-478c-806c-51deaee399e8.png">

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/10149363/187671832-4a8baeb9-65bb-430c-bb50-a20479bd70eb.png">

**Comment by knaeckeKami** [comment]
Are you on the newsest release of ferry_generator?
We have a l[ist of reserved names](https://github.com/gql-dart/gql/blob/master/codegen/gql_code_builder/lib/src/common.dart#L8) that we escape, and the newest one includes "update". 
So unless we miss escaping somewhere, this should work on the newest release.

**Comment by kerosan** [comment]
as workaround  - made alias in mutation 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/10149363/187683403-fe9b141d-1f7d-46dc-be67-affa3f175b0b.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/10149363/187683519-edaef9c8-3ba2-4547-bb7b-196145405951.png">

**Comment by knaeckeKami** [comment]
closing this for now, if you continue to have issues with the latest version please reopen
