### ISSUE TITLE
join 2 responses in one list give exception

### ISSUE THREAD

**Issue by SoloviovIvan85** [gql-dart/ferry#397]
i have 2 endpoints that returns lists of same objects i need to concat them but get error
`_$GTaskListNextQueryData_task_selectNext_items' is not a subtype of type 'GTaskListQueryData_task_list_items' of 'value'`

As you can see in both queries i use same fragments as return type.
```
# import '../fragments/TaskList.graphql'

query TaskListNextQuery($cursor: String!) {
  task {
    selectNext(cursor: $cursor) {
      ...TaskListFragment
    }
  }
}
```

```
# import '../fragments/TaskList.graphql'

query TaskListQuery($request: TasksRequest) {
  task {
    list(request: $request) {
      ...TaskListFragment
    }
  }
}
``` 

how to join responses from 2 endpoints that has same return type, generated types are different ?

**Comment by knaeckeKami** [comment]
the generated concrete types are different, but if you use the same fragment, they will have a common abstract supertype. 

in the generated code, you should find a

```dart
abstract class TaskListFragment
```

and the response types implement this TaskListFragment class.
Your can add them both to a `List<TaskListFragment>`.

**Comment by SoloviovIvan85** [comment]
Hi @knaeckeKami,
thanks for response.

 It was problem in merge code 

last code:
```
BuiltList<GTaskFragment> addTasks(BuiltList<GTaskFragment> firstList, BuiltList<GTaskFragment> secondList) {
    List<GTaskFragment> listResp = new List.of(firstList, growable: true);
    listResp.addAll(secondList);

    return listResp.build();
  }
```
