### ISSUE TITLE
Expanding fragments defined on interfaces

### ISSUE THREAD

**Issue by DoctorJohn** [gql-dart/ferry#42]
The `expandFragments` function in the normalize package only includes fragments if their type name matches the data objects type name. This is a problem if the fragment is defined on an interface. GraphQL servers return concrete typed data even when a query contains an fragment that is defined on an interface.

As an example consider the following type, interface and query (slightly inspired by the github graphql api):

```graphql
interface Actor {
    id: ID!
    avatarUrl: String!
}

type User implements Actor {
    id: ID!
    avatarUrl: String!
    name: String!
}
```

```graphql
query Users {
    users {
      ... ActorInfo
    }
}

fragment ActorInfo on Actor {
    __typename
    id
    avatarUrl
}
```

A response to this query could look something like this:

```json
"users": [
    {
        "__typename": "User",
         "id": "1",
         "avatarUrl": "http://example.com/avatar.png"
    }
]
```

Running `normalize` on it should return the following normalized map:

```json
"Query": {
    "users": [
        {
            "$ref": "UserType:1"
        },
    ],
},
"User:1": {
    "__typename": "User",
    "id": "1",
    "avatarUrl": "http://example.com/avatar.png",
}
```

In `expandFragments` the normalized map (variable `data`) is used to perform the following check:

```dart
// Only include this fragment if the type name matches
if (fragment.typeCondition.on.name.value == data["__typename"]) {
    // ...
}
```

The fragments type name will be `Actor` but the datas (concrete) type will be `User`, thus the fragment wont't be included.

**Comment by smkhalsa** [comment]
Yes, you're right. We should remove the condition for `FragmentSpreadNode`s, but we will still need to filter on __typename for `InlineFragmentNode`.
