### ISSUE TITLE
serializer builder not working when specifying `sources`

### ISSUE THREAD

**Issue by pd4d10** [gql-dart/ferry#429]
### Reproduction

1. Add several lines to `examples/pokemon_explorer/build.yaml` as follows:

```diff
targets:
  $default:
+   sources:
+     - lib/src/graphql/**
+     - lib/schema.graphql
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: pokemon_explorer|lib/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: pokemon_explorer|lib/schema.graphql
```

2. Run `dart run build_runner build` in the Pokemon explorer example

`serializers.gql.dart` and `serializers.gql.g.dart` are missing

**Comment by knaeckeKami** [comment]
When I run this, I see a warning in build_runner:

```
[WARNING] build.fallback:
The package `pokemon_explorer` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
  - lib/$lib$
```

Do you want to speed up code generation? I think that `generate_for` is supposed to be used for that.

**Comment by pd4d10** [comment]
> Do you want to speed up code generation? 

Actually, I'm trying to make multiple GraphQL schema (from different endpoints) work correctly. According to #315, it works with multiple targets, the only limitation is that `sources` of different targets shouldn't have duplicate files, or `build_runner` would throw an error due to the conflict.

After narrowing the `sources` scope, `graphql_builder` works but `serializer_builder` not

**Comment by knaeckeKami** [comment]
Does it work if you use `generate_for` instead of sources, like in the examples of #315  ?

I guess if you restrict the sources it causes an issue since serializer_builder depends on files generated by graphql_builder, and the `sources` files are evaluated before `graphql_builder` is run.
Not sure what can be done about that. 

I can offer you a workaround that will work for sure:  You can create 2 separate packages containing just the graphql schemas.

**Comment by pd4d10** [comment]
Tried `generate_for` but with no luck. 

> create 2 separate packages containing just the graphql schemas and depend on these packages in your main app

Yeah, this seems to be the last solution, considering that Ferry itself does not support multiple schemas currently. Will give it a try

Thanks for the detailed answer! Closing

**Comment by lokishengoku** [comment]
Any updates on this?

**Comment by 0p3r4t0r** [comment]
As mentioned in #315

You have to remove the generate_for from the `ferry_generator|serializer_builder`

```yaml
ferry_generator|graphql_builder:
  generate_for:
    - lib/graphql/api1/**
  enabled: true
  options:
    schema: project|lib/path_to/schema.graphql
ferry_generator|serializer_builder:
  # no generate_for
  enabled: true
  options:
    schema: project|lib/path_to/schema.graphql
```

**Comment by bambinoua** [comment]
Hi, @knaeckeKami 
> The missing sources are:
> ```
>   - $package$
>   - lib/$lib$
> ```
> 

Did you know what these `$package$` and `$lib$` contain?
