### ISSUE TITLE
allow analyzer 5.0.0

### ISSUE THREAD

**Issue by knaeckeKami** [gql-dart/ferry#430]

**Comment by sahmadreza** [comment]
`freezed >=2.1.1` depends on `analyzer ^5.0.0`, `ferry_generator ^0.6.1` is incompatible with `freezed >=2.1.1`.

**Comment by knaeckeKami** [comment]
blocked by https://github.com/google/built_value.dart/issues/1188#issue-1387692886

**Comment by ValentinVignal** [comment]
@knaeckeKami Is there any plan to push it in a stable release any time soon?

**Comment by knaeckeKami** [comment]
done. note that there were breaking bug fixes since the last stable release.
