### ISSUE TITLE
Question: Type-Safe Initialisation of query and mutation vars

### ISSUE THREAD

**Issue by okaforcj** [gql-dart/ferry#436]
Apologies for opening an issue for a question :( but i didnt see a discussion tab on this repo. I was wondering how we could ensure type-safe intiialisation of a variable. for example

``` dart
 final createXploringPostReq = GXploringPostReq(
        (b) => b
          ..vars.input.content = content
          ..vars.input.tags = tagsBuilder
          ..vars.input.countries = countriesBuilder
          ..vars.input.type = type
          ..vars.input.location = convertLocation(location),
      );
```

In the above, there is no compile time check to see if im missing a variable required by the graphql schema, is there any other way to init the request while ensuring full type-safety at compile time pleae ?

**Comment by knaeckeKami** [comment]
Discussion are mostly on Discord :) https://discord.gg/sSyq3EFd

To your question: Unfortunately no, not at the moment.
There are users looking into adding another way to generate code without using built_value. But I don't think this is going to ready soon.

**Comment by okaforcj** [comment]
@knaeckeKami  are right brilliant thanks, ill use discord for future discussions and yeah its fine i can manage to keep populating and paying extra attention.
