### ISSUE TITLE
Exposing refetching status

### ISSUE THREAD

**Issue by okaforcj** [gql-dart/ferry#439]
I noticed that we have a loading state for the initial gql fetch request but no further state to indicate that an item is actually refetching or has even been completed. Two scenarios I've now faced:

1. I am using a refetchIndicator and I don't have a way of knowing when the refetch actually completes
2. I have a dynamic request which has query variables that change, when they change I'd like to know the progress of the refetching status, a.t.m the loading state only shows on the initial request

Is there any way to manage any of the scenarios above by exposing an isRefetching param? please does anyone have advice on this?

**Comment by breathingcyborg** [comment]
@okaforcj  If you can recall, how did you solve this? Using Completer?
