### ISSUE TITLE
Cannot access response headers in Ferrygraphql

### ISSUE THREAD

**Issue by tinhok02** [gql-dart/ferry#453]
Anyone can help me how to get "set-cookie" from the headers of the response???

**Comment by GP4cK** [comment]
That may not be possible in the browser: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie.

Which platform are you using?

**Comment by tinhok02** [comment]
@GP4cK  Thanks for the reply,

My backend is implemented with Express-session. The token is always sent through the response headers to the client.  For my web platform, it is fine to accept "Set-cookie". however, for mobile platforms, I want to obtain and set the returned token to somewhere else in flutter storage. My solution is to find a way of getting HTTP headers. Also, Ferrygraphql should bring the headers along with the data. thanks

**Comment by GP4cK** [comment]
I see. Then maybe look into using a `TransformLink` and do something like this:

```dart
TransformLink(
  responseTransformer: (response) {
    final headers = response.context.entry<HttpLinkHeaders>();
    // Do what you want.
    return response;
  },
),
```

**Comment by tinhok02** [comment]
@GP4cK it supposes to work fine with your answer. But I still receive a null from context and the headers. I still don't know what i did wrong~ anyways thanks for your help. The following is how i applied TransformLink

  final link = HttpLink(
    "http://api.url/graphql",
  );

  final tranformLink = TransformLink(
    responseTransformer: (resp) {
      final headers = resp.context.entry<HttpLinkHeaders>();
      print(headers);
      return resp;
    },
  );

  final client = Client(
    link: tranformLink.concat(link),
  );

**Comment by knaeckeKami** [comment]
The context entry type  you want is `HttpLinkResponseContext`.

`HttpLinkHeaders` is for dynamically adding headers (like `Authorization` to a request.

**Comment by tinhok02** [comment]
@GP4cK @knaeckeKami it works for me. Thank you so much~ 😊

```dart
  final link = HttpLink(
    "http://api.url/graphql",
  );

  final tranformLink = TransformLink(
    responseTransformer: (resp) {
      final cookie = resp.context.entry<HttpLinkResponseContext>()?.headers?['set-cookie'];
      print(cookie);
      return resp;
    },
  );

  final client = Client(
    link: tranformLink.concat(link),
  );
```
