### ISSUE TITLE
How can I send request with null field?

### ISSUE THREAD

**Issue by bizk-sato** [gql-dart/ferry#473]
I want to update a field with null.

So I did something like below.

```
final req = GUpsertModelReq((b) {
  b.vars.input.field_name = null;

 return b;
}
await client.request(req)
```
`field_name` is nullable field in graphql schema.

when I submit the request, it doesn't send the `field_name` field.
How can I send field with null value?

**Comment by knaeckeKami** [comment]
This is currently not supported. It was a limitation of built_value when this library was written originally.

However, built_value supports this now, so we could add an option to ferry_generator to add `@BuiltValueSerializer(serializeNulls: true)` to serializers of input fields. ( https://github.com/google/built_value.dart/issues/604 )

This would, however, lead to all fields being included and being sent as null even if they were never set, so it's also not a really good solution. 

A complete fix would probably require wrapping all nullable values in something like [this](https://drift.simonbinder.eu/api/drift/value-class). 

At the moment, I can only offer you a workaround: Write your own class that implements the G...Var() type and implement your own toJson() where you decide what's included or omitted.

**Comment by bizk-sato** [comment]
@knaeckeKami 
Ok, thanks.

Can you provide sample code or how to implements the `G...Var()` type and `toJson()` method?

**Comment by knaeckeKami** [comment]
You could for example add an additional bool field `explictlySetToNull` for every variable that gets set to true to decide wether to include it in the toJson() or not.

**Comment by knaeckeKami** [comment]
Thanks for sharing a workaround!

I have a draft solution here: https://github.com/gql-dart/gql/pull/381

I am not sure when I can make it production-ready (especially tests, make this an opt-in feature to avoid breaking changes, and code cleanup).

**Comment by mattbajorek** [comment]
Extending on what @zombie6888 has posted. Here is a full example:

```dart
import 'package:built_value/serializer.dart';
// ignore: implementation_imports
import 'package:gql_code_builder/src/serializers/json_serializer.dart';

import '../../utils/date_utils.dart';
// IMPORT GQueryVars

class QueryVarsSerializer extends JsonSerializer<GQueryVars>
    implements StructuredSerializer<GQueryVars> {
  @override
  GQueryVars fromJson(Map<String, dynamic> json) {
    final builder = GQueryVarsBuilder()
      ..id = json['id']
      ..nullableField = dateTimeFromJsonValue(json['nullableField']);
    return builder.build();
  }

  @override
  Map<String, dynamic> toJson(GQueryVars object) =>
      {'id': object.id, 'nullableField': object.nullableField};

  // Required override method needed to serialize a null value
  // Needs to return a list of all of the key value pairs
  @override
  Iterable<Object?> serialize(
    Serializers serializers,
    GQueryVars object, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      ['id', object.id, 'nullableField', object.nullableField];
}
```

Then in build.yaml:

```yaml
targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          custom_serializers:
            - import: "IMPORT LOCATION"
              name: QueryVarsSerializer
```

**Comment by knaeckeKami** [comment]
Fixed by 

https://github.com/gql-dart/ferry/pull/549
and
https://github.com/gql-dart/gql/pull/381
