### ISSUE TITLE
No subscription events received

### ISSUE THREAD

**Issue by krejko** [gql-dart/ferry#486]
I have been able to setup a subscription endpoint that I can access and use successfully through the apollo studio sandbox web application. However, I am unable to access these events through the ferry subscription implementation. I can see via the logs that the subscription listen is taking place, but when I trigger an event on the backend the `onData` function of the subscription is never called. 

Have I set up my subscription client incorrectly? Or is there a recommended next step in debugging what's going on here? 

Update: I can see in the network inspector that the `/graphql` websocket is repeatedly returning `101 Switching Protocols`. Any idea why or what I should do about it?

Update 2: I have temporarily specified `wsLink` as the `link` for the `Client` class to rule out any confusion created by the `Link.Split` code. Unfortunately it still repeats `101 Switching Protocols` for the `/graphql` websocket in the network inspector. 

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:frontend/utils/graphql.dart';
import 'package:frontend/app.dart';

Future<void> main() async {
  await GraphQL.init();
  runApp(await App.initialize());
}
```

graphql.dart
```dart
import 'constants.dart';
import 'package:gql_http_link/gql_http_link.dart';
import 'package:ferry/ferry.dart';
import 'package:get_it/get_it.dart';
import "package:gql_websocket_link/gql_websocket_link.dart";
import 'package:gql/ast.dart';

class GraphQL {
  static init() async {

    final httpLink = HttpLink('http://${Constants.apiUrl}/graphql');
    final wsLink = WebSocketLink(
      'ws://${Constants.apiUrl}/graphql',
       autoReconnect: true,
       reconnectInterval: const Duration(seconds: 5),
    );
    final link = Link.split((request) {
      return GraphQL.isSubscription(request.operation.document);
    }, wsLink, httpLink);

    final client = Client(
      link: link,
    );

    GetIt.I.registerLazySingleton<TypedLink>(() => client);
  }

  static bool isSubscription(DocumentNode document) {
    return document.definitions.whereType<OperationDefinitionNode>().first.type == OperationType.subscription;
  }
}

```

recipes.provider.dart
```dart
import 'package:flutter/material.dart';
import 'package:frontend/graphql/generated/recipes.update.subscription.req.gql.dart' as subReq;
import 'package:frontend/providers/auth.provider.dart';
import 'package:get_it/get_it.dart';
import 'package:ferry/ferry.dart';

class Recipes with ChangeNotifier {

  final client = GetIt.I<TypedLink>();
  late Auth auth;
  var loading = false;

  Recipes(this.context) {
    auth = Provider.of<Auth>(context, listen: false);
    subscribe();
  }

  subscribe() {
    var subscription = subReq.GSubscriptionReq(
        (b) => b..vars.ownerUuid = auth.payload?['user_id']);
    print("subscribing");
    client.request(subscription).listen((res) {
      if (res.hasErrors) {
        print('errors ${res.linkException}');
      }
      print("Subscription response ${res.data?.recipeUpdated}");
    }, onError: (error) {
      print("Error $error");
    }, onDone: () {
      print("Done");
    });
  }

}
```

recipe.subscription.graphql
```graphql
subscription Subscription($ownerUuid: String) {
  recipeUpdated(ownerUuid: $ownerUuid) {
    createdAt
    deleteAt
    displayName
    modifiedAt
    uuid
  }
}
```

debug console
```
subscribing
```

**Comment by knaeckeKami** [comment]
Do you see any errors on the server side?

It's possible that the server only supports a different websocket protocol (graphql-transport-ws).

There are two, and at the moment, websocket client only supports the older one.

There is open open PR for the new protocol: https://github.com/gql-dart/gql/pull/355 (it's not fully ready yet I think though) and there is an implementation of the new protocol in the  graphql package:

**Comment by krejko** [comment]
There are no serverside errors. Just me loading the apollo studio sandbox
```
=================================
======= ENV: development =======
🚀 App listening on the port 3001
=================================
2023-02-07 17:38:44 info: GET /graphql 200 4.800 ms - -
```

Following [this post](https://stackoverflow.com/questions/68947905/how-can-i-make-flutter-graphql-subscription-work-with-ferry-package), I did start to experiment with the protocol as you also just suggested. I confirmed I am using the `graphql-ws` library on the backend which implements the `graphql-transport-ws` protocol, as you can see in the updated code snippet below. 

```
    final wsLink = WebSocketLink(
      // 'ws://${Constants.apiUrl}/graphql',
      null,
      autoReconnect: true,
      reconnectInterval: const Duration(seconds: 5),
      channelGenerator: () => WebSocketChannel.connect(
          Uri.parse('ws://${Constants.apiUrl}/graphql'),
          protocols: ['graphql-transport-ws']),
    );
```

This doesn't yield any errors in the console, but does the repeated `101 Switching Protocols` network requests. If I update the protocol to `graphql-websites` as if I were using the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) library in the backend I get the following error: 
```error
html_dart2js.dart:31915 WebSocket connection to 'ws://localhost:3001/graphql' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
_create_1 @ html_dart2js.dart:31915
new @ html_dart2js.dart:31910
html$.HtmlWebSocketChannel.connect @ html.dart:76
connect @ _connect_html.dart:16
connect @ channel.dart:115
(anonymous) @ graphql.dart:25
_connect$ @ link.dart:228
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_connect] @ link.dart:225
request$ @ link.dart:160
runBody @ async_patch.dart:325
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
errors.dart:299 Uncaught (in promise) Error: WebSocketChannelException: WebSocket connection failed.
    

    at Object.createErrorWithStack (errors.dart:299:10)
    at Error._throw (core_patch.dart:355:28)
    at Error.throwWithStackTrace (errors.dart:120:5)
    at async._AsyncCallbackEntry.new.callback (zone.dart:1385:11)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:166:15
```

This makes me think I've got the protocol correct, and also that it's using the correct protocol by default.

**Comment by krejko** [comment]
Ah, I think I see what you are saying. I am using the newer one so I'll need to copy the proposed implementation into my project.

**Comment by krejko** [comment]
@knaeckeKami Thank you for pointing me in the correct direction. I had to do some [small modifications](https://github.com/gql-dart/gql/pull/355#issuecomment-1423012048) to the pull request you referenced above, but in the end I was able to get it working. 

To help anyone else that's running into this issue, I'll leave my working code below:

graphql.dart
```dart
import 'dart:async';

import 'package:frontend/providers/auth.provider.dart';

import 'constants.dart';
import 'package:gql_http_link/gql_http_link.dart';
import 'package:ferry/ferry.dart' as ferry;
import 'package:get_it/get_it.dart';
import 'package:gql/ast.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'graphql_transport_ws.dart';

const autoReconnect = true;
const reconnectDuration = Duration(seconds: 10);
const inactivityTimeout = Duration(seconds: 5);

class GraphQL {
  static init(Auth auth) async {

    final httpLink = HttpLink('http://${Constants.apiUrl}/graphql');

    final wsLink = GQLTransportWebSocketLink(ClientOptions(
      socketMaker: WebSocketMaker.generator(() => WebSocketChannel.connect(
          Uri.parse('ws://${Constants.apiUrl}/graphql'),
          protocols: ['graphql-transport-ws'])),
      connectionParams: () => {"Authorization": "Bearer ${auth.token}"},
      keepAlive: inactivityTimeout.inMilliseconds,
      connectionAckWaitTimeout: inactivityTimeout.inMilliseconds,
      retryAttempts: autoReconnect == false ? 0 : 5,
      retryWait: (_) => Future.delayed(reconnectDuration),
      on: [
        //TODO: Remove once finsihed testing
        TransportWsEventHandler<void>(
          connected: (WebSocketChannel socket, Object? payload) {
            print("Websocket Connected");
          },
        ),
      ],
    ));

    final link = ferry.Link.split((request) {
      return GraphQL.isSubscription(request.operation.document);
    }, wsLink, httpLink);

    final client = ferry.Client(
      link: link,
    );

    GetIt.I.registerLazySingleton<ferry.TypedLink>(() => client);
  }

  static bool isSubscription(
    DocumentNode document,
  ) {
    return document.definitions
            .whereType<OperationDefinitionNode>()
            .first
            .type ==
        OperationType.subscription;
  }
}

```

Be sure you add [transport_ws_common.dart](https://github.com/gql-dart/gql/pull/355/files#diff-59cb0073e322957f58304c396546608f966689fdb06e57a5330bcdb8e1c37a88) and [graphql_transport_ws.dart](https://github.com/gql-dart/gql/pull/355/files#diff-bed26baaef0508883e9e659eb02a2a53ce391c166ac59e5d6714d205cf339da3) to your project. Then you will need to import graphql_transport_ws.dart in your graphql file where you setup your client and make your websocket `Link` from the `GQLTransportWebSocketLink` class.
