### ISSUE TITLE
Please make the documentation more clear

### ISSUE THREAD

**Issue by MattGson** [gql-dart/ferry#49]
Hey, I have been trying out Ferry after getting very frustrated with graphql_flutter. So far the project looks like it is designed better but I have not spent much time with it yet. 

One of the issues I am running into is the lack of documentation. There is currently one very thin example to go off. The large number of dependencies is also very confusing and will potentially be a nightmare to keep versions in sync (I've already run into conflicts). It would be ideal if the ferry flutter client could be installed as a single package which would include all required codegen/gql packages etc. I think that will be key to increasing adoption of Ferry.

Also, as a side note, it would be awesome if there was a hooks API. Coming from React/Apollo client, working with GraphQL in Flutter is currently extremely clunky. I think this library has the potential to change that.

**Comment by smkhalsa** [comment]
Thanks for the feedback. Yes, the documentation definitely needs improvement.

Since I'm the only maintainer, I've been hesitant to put a lot of effort into docs until I feel the API is stable.

However, PRs are always welcome.

**Comment by MattGson** [comment]
I'd be keen to put some PRs up but not sure my understanding is good enough in order to write docs yet.

**Comment by smkhalsa** [comment]
Now that v0.5.0 is published, I intend to put some time and effort into docs.

Here are some topics that I'd like to cover:

- [ ] initial setup
- [ ] generating / using built_value data classes
- [ ] pagination
- [ ] refetching
- [ ] updateCacheHandlers (including using CacheProxy)
- [ ] direct cache access
- [ ] error handling
- [ ] using with flutter / ferry_flutter

Please feel free to recommend additional topics.

**Comment by smkhalsa** [comment]
I'm also looking into options for doc sites. I'm leaning towards just using dartdoc since it plays well with the dart ecosystem.

**Comment by ram231** [comment]
I'd love to see a documentation on the type generation or using build runner.

**Comment by smkhalsa** [comment]
@MattGson 

I've added a new documentation site. Please check it out and let me know what additional documentation you'd like to see.

https://ferrygraphql.com/
