### ISSUE TITLE
Delayed parsing

### ISSUE THREAD

**Issue by zombie6888** [gql-dart/ferry#495]
I have junks on page animations when i parse a big json data. For mobile and desktop applications i can use isolates and it works very good. I have no junks there. But it's not supported for web. Probably it's a not a good solution but can i use queries in this sequence: run query, get response, wait for page animations finished and then parse response?

**Comment by knaeckeKami** [comment]
Are you sure it's parsing that is the issue and not normalization / de-duplication of updates?
Does that jank also happen when so set the CachePolicy to .NoCache?

**Comment by zombie6888** [comment]
It's only happens with big data. if i limit response or use paginated queries, i don't see any junks. And when i use isolates there is no junks. It's nice to have but not so bad If it's not supported

**Comment by zombie6888** [comment]
Now i think it wouldn't make sense. Anamation takes about 200-300ms. If i get network response more than 300 ms it doesn't affect animation. But when i get response from 10 - 100 ms i see junks (we just moved from cloud to self host hasura server).  10-100 ms delay is not a big problem. I can run both query and parsing after animation finished. And there are many options like using pagination on big data or disable page loading animation which is better for this. Close this issue.
