### ISSUE TITLE
Need a way to refetch the query

### ISSUE THREAD

**Issue by MattGson** [gql-dart/ferry#50]
There is currently no way to refetch a query manually with the same variables.

Even if the fetch policy includes the network i.e. CacheAndNetwork, I currently have to use a key to force the parent widget of the query to reload when refetch is required.

Ideally, the network policy could be set to CacheFirst and then the query manually refetched as required.

**Comment by smkhalsa** [comment]
The following should cause a query response stream to update:

1. Add a queryId to the original query
2. Creat a second QueryRequest that uses the same queryId (can have a different fetch policy than the original)
3. Manually add the second QueryRequest to the client's queryController.

**Comment by smkhalsa** [comment]
I'm closing for now, but let me know if the above doesn't work for you and I'll reopen.

**Comment by jrvidotti** [comment]
Hi @smkhalsa!

I am trying to implement a "Refresh Button" in a screen with a Operation widget that render a list. I readed docs in https://ferrygraphql.com/docs/pagination/#refetching but I didn't got it going.

**Comment by smkhalsa** [comment]
@jrvidotti if you are using an identical request (or a request with the same requestId), it should be working.

Can you write a failing test or provide a minimum repro?

**Comment by jrvidotti** [comment]
> @jrvidotti if you are using an identical request (or a request with the same requestId), it should be working.
> 
> Can you write a failing test or provide a minimum repro?

Here it is: https://github.com/jrvidotti/ferry_cache_unexpected_behaviour

**Comment by smkhalsa** [comment]
@jrvidotti it looks like this is working as expected.

The default FetchPolicy for Query operations is `CacheFirst`, so when you are tapping on the refresh icon, you are getting back the initial cached data, and it never reaches the server.

**Comment by jrvidotti** [comment]
Oh, my bad! What a dumb mistake.

But I think Refetching could have a warning about FetchPolicy... can I make a Pull Request to the docs?

**Comment by smkhalsa** [comment]
No worries. 

> can I make a Pull Request to the docs?

Sure, that'd be helpful. https://github.com/gql-dart/ferry-docs

**Comment by jrvidotti** [comment]
https://github.com/gql-dart/ferry-docs/pull/2
