### ISSUE TITLE
When FetchPolicy is CacheAndNetwork and offline no response from cache

### ISSUE THREAD

**Issue by francescreig** [gql-dart/ferry#501]
Hello,

I have one small issue. When I set my default fetch policy `FetchPolicy.CacheAndNetwork` and when I am offline, when I am using the `Operation` widget, I did not receive any response form the cache, even though I have the information cached (when I switch to `CacheFirst` in offline, it returns data from the cache). 

Do you know why it could happen? 

Thank you in advance

**Comment by knaeckeKami** [comment]
can you share a reproducible example?

**Comment by francescreig** [comment]
Closing since it was outdated. There was a misunderstanding when creating the OfflineMutationTypedLink
