### ISSUE TITLE
Add a way to generate classes for some types in the schema 

### ISSUE THREAD

**Issue by ValentinVignal** [gql-dart/ferry#527]
I have this schema:

```graphql
# lib/schema.graphql

type Pokemon {
  id: ID!
  name: String!
  type: String!
}

type Query {
  pokemons: [Pokemon!]!
  pokemon(id: ID!): Pokemon
}
```

And let's consider I have those 2 queries: 

```graphql
# lib/graphql/query.pokemon_0.graphql

query Pokemon0($id: ID!) {
  pokemon(id: $id) {
    id
    name
    type
  }
}
```

```graphql
# lib/graphql/query.pokemon_1.graphql

query Pokemon1($id: ID!) {
  pokemon(id: $id) {
    id
    name
    type
  }
}
```

I'm my code I would like to use a type (ex: `GPokemon`) that would match the type of the graphql type `Pokemon`:

```dart
class GPokemon {
  final String id;
  final String name;
  final String type;
}


void main() {
  final pokemon = GPokemon(/* ... */);
}
```

I don't want to use `GPokemon0_pokemon` or `GPokemon1_pokemon` as I don't want this type to be linked to a request, but only to the schema.

Is there a way to do this already, if not, would it make sense to create something for that?

**Comment by knaeckeKami** [comment]
The way do to this with ferry is to use a fragment

```graphql
fragment BasePokemonInfo on Pokemon {
    id
    name
    type
}
```

and then reuse this fragment

```graphql
query Pokemon0($id: ID!) {
  pokemon(id: $id) {
    ...BasePokemonInfo
  }
}

```

```graphql
# lib/graphql/query.pokemon_1.graphql

query Pokemon1($id: ID!) {
  pokemon(id: $id) {
     ...BasePokemonInfo
     weight
  }
}

```

This will generate an abstract class `GFullExperimentFragment` and the types on both queries will implement this fragment.

**Comment by ValentinVignal** [comment]
Thank you for the suggestion! 
Would the`GBasePokemonInfoFragment` still be generated if it is not used in any query?

**Comment by knaeckeKami** [comment]
I think so. If not, please file a bug ;)

**Comment by knaeckeKami** [comment]
Does that fit your usecase?

It's a little different than what you described, but I think it's safer this way.
If we generated the full type and you used that in your code, your code might break if an additional field is added to the schema.

**Comment by ValentinVignal** [comment]
I should fit my use case yes, thank you! I still need to try it out

**Comment by ValentinVignal** [comment]
I created a fragment (unused anywhere, but it could be used):

```grapqh
# lib/graphql/fragment.pokemon.graphql

fragment PokemonFragment on Pokemon {
  id
  name
  type
}
```

The generator did create a `GPokemonFragmentData` class that I can use 


```dart
// lib/main.dart
void main() {
  final pokemon = GPokemonFragmentData(
    (pokemon) => pokemon
      ..id = 'id'
      ..name = 'name'
      ..type = 'type',
  );
}
```

---

Thank you @knaeckeKami, it did fit my use case and is probably safer than what I was asking initially!

Closing the issue
