### ISSUE TITLE
Unable to use types directly with conditional fragment spreading

### ISSUE THREAD

**Issue by rishabh-os** [gql-dart/ferry#534]
Hi, I am trying to use the schema for an app, whose schema can be found [here](https://github.com/omnivore-app/omnivore/blob/main/packages/api/src/schema.ts).

I have two queries:
```graphql
query User {
  me {
    id
    name
  }
}
``` 
```graphql
query allLabels {
  labels {
    ... on LabelsSuccess {
      labels {
        id
        name
      }
    }
    ... on LabelsError {
      errorCodes
    }
  }
}
```
My dart code is as follows:
```dart
var user = GUserReq();
var labels = GallLabelsReq()
var user_result = await ferryClient().request(user).first;
var label_result = await ferryClient().request(labels).first;
```
I can access all the fields in the first query with `user_result?.me?.id`, as expected.

However, for the second query, I have to do the following:
```dart
List y = label_result.data?.labels.toJson()['labels'];
var first_label = GallLabelsData_labels__asLabelsSuccess_labels.fromJson(y[0]);
```
Ideally, I would want to access the data in the same way as for the first query with something like `label_result.data?.labels?.id`.

From what I can tell the types are being generated properly, but the `GallLabelsData_labels` class does not have the getter for `label`.

I'm not sure if this is an error on my end. Any way to avoid having to convert to and from JSON and access the types directly?

**Comment by knaeckeKami** [comment]
since you use a type conditions, you need to do type checks before you can access the values.

You can either do manual type checks , e.g.  using pattern matching

```dart
if (result case GallLabelsData_labels__asLabelsSuccess_labels(:final id, :final name) {
   print(id);
   print(name);

}
```

or just plain old type checks with smart casts:

if (result is GallLabelsData_labels__asLabelsSuccess_labels) {
   // result is now smart-casted
   print(result.id);
   print(result.name);
}

of you can add when-extensions in your build.yaml:

```
      when_extensions:
        when: true
        maybeWhen: true
```

see: https://ferrygraphql.com/docs/codegen/#config

and call 
```

result.when(
   labelsSuccess: (data) => ...
   labelsError: (data) => ...
);

```

**Comment by rishabh-os** [comment]
Thank you for your reply! In hindsight I can't believe I missed the docs on this. ~~they were right there!!!~~

I have decided to go with the third approach you have described.
