### ISSUE TITLE
FIle Upload error

### ISSUE THREAD

**Issue by incrediblezayed** [gql-dart/ferry#535]
Hello, 
I've already gone through the existing issue about multipartfile, but now I'm facing a new issue (it was working a few months back)
 I'm stuck with 
```
NoSuchMethodError: Class 'FormData' has no instance method '[]'.
Receiver: Instance of 'FormData'
Tried calling: []("query")) 
```
any idea why this might be?

**Comment by knaeckeKami** [comment]
please share more information about your setup, you queries, isolate client or standard client, fetchpolicy, etc.

**Comment by knaeckeKami** [comment]
closed because of inactivity
