### ISSUE TITLE
[FerryGenerator] Query generator adds all types as document nodes

### ISSUE THREAD

**Issue by daniel-possienke** [gql-dart/ferry#537]
Hi,
I'm new to GraphQL, so maybe this is not a problem with this package:

When I run the code generator, it adds all types as `definition` to the `DocumentNode`. When I run the query, I'm getting a `GRAPHQL_VALIDATION_FAILED` result from our backend. This doesn't happen when I just add the actual `OperationDefinitionNode` as a `definition` to the `DocumentNode`.

Here is an example of what I'm trying:

This is an example graphql schema I'm generating:
```
type Query {
    hello: String
}
query Hello {
    hello
}
enum Language {
    ENGLISH
}
```

The `DocumentNode` which is generated by this schema in the *.ast.gql.dart file looks like this:
```
 const document = _i1.DocumentNode(definitions: [
  Query,
  Hello,
  Language,
]);
```

When I'm using this [graphql generator](https://pub.dev/packages/graphql_codegen) the DocumentNode looks like this:
```
const documentNodeQueryHello = DocumentNode(definitions: [
  OperationDefinitionNode(
    ...
  ),
]);

```

It seems that our backend can't handle the way the other definitions are added to the `DocumentNode`. 

So my question is, is there an easy way to not add the additional definitions as part of the DocumentNode to the query?

**Comment by knaeckeKami** [comment]
```graphql
type Query {
    hello: String
}
query Hello {
    hello
}
enum Language {
    ENGLISH
}
```

this is not a valid grapqhl schema.
the schema should not contain concrete queries like

```graphql
query Hello {
    hello
}
```

**Comment by daniel-possienke** [comment]
Thanks for the answer. My problem was that I've added the query to the same `graphlql` file as the schema. After separating these files only the necessary definitions are added.
