### ISSUE TITLE
[question] Is the header of a request cached?

### ISSUE THREAD

**Issue by II11II** [gql-dart/ferry#542]
Ferry does not update the cache if header values are not the same as the old request.

The 1 st request 
```
*** Request ***
operationName: GetInfo
headers request:
phone_number: 45345235432 
authorization: Bearer ************
content-type: application/json

document:
"query GetInfo()"
...
```
The 1 st response
```
{
data: {
"phone": 45345235432,
"some_info": "request 1",
}
}
```
 

The 2 st request 
```
*** Request ***
operationName: GetInfo
headers request:
phone_number: 45345235432 <- the same as the 1st request
authorization: Bearer ************
content-type: application/json

document:
"query GetInfo()"
...
```

The 2 nd response (it gets from cache, as expected behaviour)
```
{
data: {
"phone": 45345235432, <- the same as the 1st response
"some_info": "request 1", <- the same as the 1st response
}
}
```

The 3rd request 

```
*** Request ***
operationName: GetInfo
headers request:
phone_number: 52353425342 <- it is changed 
authorization: Bearer ************
content-type: application/json

document:
"query GetInfo()"
...
```

The 3 rd response (it gets from the cache, but it has to do the request to the remote server, as the phone_number is changed in the header request )
```
{
data: {
"phone": 45345235432, <- the same as the 1st and 2nd response
"some_info": "request 1", <- the same as the 1st response and 2nd response
}
}
```

**Comment by knaeckeKami** [comment]
It's a graphql cache that's http agnostic. if want the query to be invalidated when the phone number changes, make phone number an argument of the query.

**Comment by II11II** [comment]
@knaeckeKami thank you for your reply.

I cannot pass the phone number as my GraphQL query does not accept it.

Is it possible to include HTTP headers while caching?

**Comment by knaeckeKami** [comment]
no. the graphql cache is transport protocol agnostic and does not take HTTP headers into consideration.

**Comment by II11II** [comment]
For now, Ill close the issue and will try your suggestion
