### ISSUE TITLE
writeQuery does not emit new event for request stream after modifying TypePolicy in cache

### ISSUE THREAD

**Issue by LiLatee** [gql-dart/ferry#562]
Hi!
I've spent a few hours trying to investigate it and I don't know what's the problem.
I have such a function for clearing some list in the cache. It works fine. Stream emits new data with the cleared list of items.
<img width="584" alt="image" src="https://github.com/gql-dart/ferry/assets/30510627/dd3c6a17-26b4-494e-8a84-f9cd2ae74e2e">

But after adding such TypePolicy to the cache then it does not work.
<img width="328" alt="image" src="https://github.com/gql-dart/ferry/assets/30510627/d5cc056b-e811-42a8-9c0e-63c990ee7796">
<img width="287" alt="image" src="https://github.com/gql-dart/ferry/assets/30510627/f3472679-13cb-4172-b7cf-c2362fc4dea3">

I mean that the cache is modified properly, but the stream does not emit new data in order to refresh page content.
In both cases event is printed in the first screenshot at line 137.

Why is that happening? 🤔

**Comment by knaeckeKami** [comment]
Good question!

I don't know yet, but I see something wrong:If the RootQueryType is your root query type, you should add this to your type policy. 

This might be it. 

See https://ferrygraphql.com/docs/cache-configuration#overriding-root-operation-types-uncommon

**Comment by LiLatee** [comment]
Oh my God, you are right! I had that before, but I don't know why I removed it...
After indicating that `RootQueryType` is my queryType it works fine ❤️ 
<img width="284" alt="image" src="https://github.com/gql-dart/ferry/assets/30510627/73302054-d718-4c4b-8a24-3f204de6ba85">
