### ISSUE TITLE
[Update] Update ferry_generator analyzer

### ISSUE THREAD

**Issue by nathan-poncet** [gql-dart/ferry#563]
Currently ferry_generator >=0.7.0-dev.0 depends on analyzer >=4.2.0 <6.0.0.
Some deps in my project depend on analyzer 6.0.0.

PLS update it :)

**Comment by rneswold** [comment]
Yes, please update this dependency. I'd like to build from my schemas without seeing warnings.

**Comment by knaeckeKami** [comment]
Will do soon. You can probably use a dependency_override in the meantime though, I don't think the analyzer had breaking changes that affect ferry in 6.0.0

**Comment by rneswold** [comment]
`dependency_override` is a nice workaround. Thanks.

It only works with `analyzer: ^6.2.0`, though. Apparently 6.3.0 needs an update to `meta` which is not currently in Flutter stable.
