### ISSUE TITLE
How to remove the `__typename` in the `toJson` of a fragment

### ISSUE THREAD

**Issue by ValentinVignal** [gql-dart/ferry#573]
It is a follow-up of https://github.com/gql-dart/ferry/issues/527

I have a schema

```graphql
# lib/schema.graphql

type Pokemon {
  id: ID!
  name: String!
  type: String!
}

type Query {
  pokemons: [Pokemon!]!
  pokemon(id: ID!): Pokemon
}
```

and created a fragment 

```graphql
# lib/graphql/fragment.pokemon.graphql

fragment PokemonFragment on Pokemon {
  id
  name
  type
}
```

The issue I have now is that the `G__typename` field is included as `__typename` in the json generated from the `toJson()`. Is there a way to not include `__typename` in some scenarios?

**Comment by knaeckeKami** [comment]
hm, there's the `add_typenames` option for code generation. But I would not recommend deactivating this globally, especially if you use inline fragments with type conditions.
