### ISSUE TITLE
TypePolicy is broken Or there is no clear documentation about it.

### ISSUE THREAD

**Issue by ebsangam** [gql-dart/ferry#597]
I am trying to merge paginated result into the cache but it very difficult to implement and eventually it does not work. I am facing following issue and don't know how to solve.

- `TypePolicy` are not type safe. Everything is dynamic hence makes it difficult to implement.
-  After successfully adding `TypePolicy`, the merge function does not work as expected and it throws `PartialDataException`.
- After adding `ReadPolicy` it does solve `PartialDataException` but throws type error as internally ferry tries to type cast a List of object as String.

 I have this example to reproduce the issue. https://github.com/ebsangam/graphql_caching

**Comment by knaeckeKami** [comment]
The repro does have non-public dependencies, I can't run it.
It's also very big and has a lot of files and architecture. It also does not seem to actually use any type policies. Could you reproduce a more minimal example?

Or just show, with what data does the merge function get called, how do you merge them, and how does the exception get triggered?

**Comment by ebsangam** [comment]
Thank you for quick response. I will provide you minimal example.

**Comment by ebsangam** [comment]
I have push a new branch without local dependency. https://github.com/ebsangam/graphql_caching/tree/minimal-example 
This still has uses injectable/get_it for DI. I should run on you machine. Let me know if I need to remove injectable/get_it too.

**Comment by knaeckeKami** [comment]
What are the steps to reproduce the issue?

**Comment by ebsangam** [comment]
I have just updated the branch and removed all dependencies to third party packages that was not needed to reproduce the issue. https://github.com/ebsangam/graphql_caching/tree/minimal-example
To reproduce:
- open the app, it will load page 1
- press floating button, it will load page 2
It will throw `PartialDataException`.

**Comment by ebsangam** [comment]
Be sure to pull the latest changes.

**Comment by ebsangam** [comment]
@knaeckeKami also uncomment `typePolicies` in `/ferry/client.dart`. I missed to uncomment.

**Comment by knaeckeKami** [comment]
I can't seem to get it working. but I think you return a list of posts in your merge callback, when you should return a map that matches PostPage

**Comment by ebsangam** [comment]
Oh thanks. Solved. I am dumb to forget this when using dynamic types.

**Comment by ebsangam** [comment]
However we can make another ticket to make type policy type safe. It is too hard to work with dynamic types. What do you think?

**Comment by ebsangam** [comment]
Ok for now I am closing this issue. Thanks for your help.
