### ISSUE TITLE
Error: 'Context' isn't a type

### ISSUE THREAD

**Issue by letsar** [gql-dart/ferry#609]
When using ferry_generator 0.12.0, I have generated code which does not compile.
The error is **Error: 'Context' isn't a type**.
It looks like there is a prefix for the import missing: 
I have this code generated
```dart
value = object.context;
    if (value != null) {
      result
        ..add('context')
        ..add(serializers.serialize(value,
            specifiedType: const FullType(Context)));
    }
```

 It seems that if I put the right prefix (_i4), it should work.
```dart
value = object.context;
    if (value != null) {
      result
        ..add('context')
        ..add(serializers.serialize(value,
            specifiedType: const FullType(_i4.Context)));
    }
```

Did I do something wrong?

**Comment by knaeckeKami** [comment]
Hi!

Seems like a bug, context should not be serialized. 

I'll look into it. 

If you can produce a reproducible example, I would appreciate it.

**Comment by letsar** [comment]
Ok I'll try to find a way to reproduce it. It seems to be only with our code, maybe we did do something not conventional ^^.

**Comment by letsar** [comment]
I know what was the issue. We still had generated code from deleted queries. After I deleted these files, it was fine. Sorry for the issue 😬 .
