### ISSUE TITLE
flutter build process fails when using a package without ferry_flutter

### ISSUE THREAD

**Issue by Yakiyo** [gql-dart/ferry#615]
Hi, i've recently did a small flutter project and had to use a graphql api. For that i made a separate dart package in a subdirectory and used the `ferry` package, not the `ferry_flutter`. When i later used that package in my main flutter app, the flutter build fails with the following errors: 
![image](https://github.com/user-attachments/assets/a23bf8cf-0dae-4594-814d-ffe3e795511f)
Which actually made me very confused, because the package was working fine since my tests were running okay. The flutter app itself was fine right until i added the package. And i didnt understand the error messages cz im still new to flutter. I later found that adding `ferry_flutter` to the flutter app adds the `gql_code_builder_serializers` package as a dependency, which idk why is not being included from the package using just `ferry` and then the build procedure worked fine. I never added the ferry_flutter pkg bcz my app doesnt really require that much complicated stuff for me to require the widget that comes from ferry_flutter. 
Not sure if im the first to experience this issue. I suggest this should be mentioned in the documentation, to explicitly include the code builder serializers pkg if ferry flutter is not being used.

The exact state of my project during this issue can be found here:
https://github.com/Yakiyo/aldesk/tree/ff5d8353419b55dc012dbef6ae87b193d9182c5d
in case someone wants to reproduce it.
`anilist` directory is the package that uses ferry

**Comment by knaeckeKami** [comment]
please add gql_code_builder_serializers to your dependencies

see

https://ferry.gql-dart.dev/docs/setup
