### ISSUE TITLE
Consider making cache methods async

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/ferry#64]
This would allow for `Store` implementations not stored in memory, such as:

https://docs.hivedb.dev/#/advanced/lazy_box?id=lazy-box

**Comment by agent3bood** [comment]
Is it possible to make `Store` methods async? I am writing a custom store for `moor` package and it returns `Future`s.

**Comment by smkhalsa** [comment]
No, not without reworking the entire cache.

**Comment by agent3bood** [comment]
I am trying to solve this, most of the work is in the `normalize` package, because it it using the `read` function everywhere.

**Comment by smkhalsa** [comment]
Yes, this is not a trivial change. It would require a complete rework of normalize and the ferry cache (and would be a breaking change for the cache access methods).

We also would want to ensure there isn't a significant performance hit to sync Store implementations.

Finally, I'm not completely convinced that we'd want to exclude all use cases that require sync access.

**Comment by agent3bood** [comment]
Thanks for the answer
