### ISSUE TITLE
how to upload files

### ISSUE THREAD

**Issue by linja041** [gql-dart/ferry#66]
As the title says I want to upload a pictures,  but I don't know how to use ` scalar Upload` .
Please tell me the way,  thanks.

**Comment by smkhalsa** [comment]
I just added some [documentation](https://ferrygraphql.com/docs/custom-scalars) for using custom `scalar` types.

**Comment by biklas7** [comment]
@smkhalsa don't see any example on the documentation regarding this :thinking: maybe I'm doing something wrong but I can't upload files.

I have the `type_override` for the `scalar Upload`:
```
Upload:
  name: MultipartFile
  import: 'package:http/http.dart'
```

But when I try to run any upload operation it throws `LinkException(Bad state: No serializer for 'MultipartFile'.)`.

But how do you implement a serializer for this? Tried multiple times to no avail. I've searched everywhere for an example and I know that this is supported, but the documentation doesn't say anything about file uploads specifically.

**Comment by smkhalsa** [comment]
@biklas7 did you read the docs on [creating](https://ferrygraphql.com/docs/custom-scalars/#create-a-custom-serializer) and [configuring](https://ferrygraphql.com/docs/custom-scalars/#configure-custom-serializer) a custom serializer?

If so and you're still struggling, I recommend asking for help on the Discord. I don't use GraphQL file uploads, but I know others do.

**Comment by biklas7** [comment]
Yes I did, I'm using custom serializers for other scalar types, but for this one, it isn't working. I will ask there and If I get some help, I will reply here. Thx :+1:

**Comment by AGKhalil** [comment]
@biklas7 Did you figure out how to serialize MultipartFile? It'd be awesome if you can post the solution here.

**Comment by biklas7** [comment]
@AGKhalil To be honest with I still haven't solved the problem. It would be awesome to find this on the documentation and with an sample project :pray:

**Comment by lotus-x** [comment]
Have you tried creating a multipart image using http?

```dart
    // create multipart file
    final multipartImage = await http.MultipartFile.fromPath(
      '',
      image!.path,
      contentType: MediaType.parse(lookupMimeType(image!.path)!),
    );
```

**Comment by p02diada** [comment]
Hi @biklas7  @AGKhalil  @linja041 I have written an article in medium explaining how to do it: https://link.medium.com/gIJHjREi8hb

**Comment by incrediblezayed** [comment]
@p02diada I'm facing issue now
Thank You for this great solution, I did implement it and it was working until last month, but now, I'm stuck with NoSuchMethodError: Class 'FormData' has no instance method '[]'.
Receiver: Instance of 'FormData'
Tried calling: []("query")) any idea why this might be?
