### ISSUE TITLE
prevent subscription from adding __typename

### ISSUE THREAD

**Issue by iscriptology** [gql-dart/ferry#81]
As per the GraphQL spec, subscriptions must include one and only one root field [including introspection fields](https://spec.graphql.org/June2018/#example-2353b).

I have a `MessageReceived` subscription with one root field:
```graphql
subscription MessageReceived {
    messageReceived {
        prevMessageTimestamp
        message {
            ...on TextMessage {
                ...FullTextMessage
            }
            ...on RecordingMessage {
                ...FullRecordingMessage
            }
            ...on TypingMessage {
                ...FullTypingMessage
            }
            ...on PresenceMessage {
                ...FullPresenceMessage
            }
        }
    }
}
```
 and for some reason I get `Subscription "MessageReceived" must select only one top level field.` error message.

I hight suspect that addTypename functionality automatically adds __typename to my subscription and therefore invalidating it.

1) Is there a way to prevent a certain request from adding the __typename?
2) In general I think we should prevent addTypename on the root `Subscription` type.

**Comment by smkhalsa** [comment]
Thanks for reporting this. Can you please check that #83 resolves the issue?

**Comment by smkhalsa** [comment]
Actually, I just realized that this needs to be changed in gql_build as well, so #83 alone likely won't resolve the issue.

**Comment by smkhalsa** [comment]
Oh, nevermind. The changes in gql_build wouldn't affect the operation itself. So #83 should be sufficient to fix this.

**Comment by smkhalsa** [comment]
@iscriptology can you confirm that you have subscriptions working? What link are you using?

**Comment by iscriptology** [comment]
A customized version of gql_websocket_link. And yes indeed they work after this fix.
