### ISSUE TITLE
Consider removing Query Widget

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/ferry#9]
I'd like to keep the API footprint as minimal as possible without sacrificing core functionality.

The `Query` widget is a very light wrapper around `StreamBuilder`. `StreamBuilder` [re-subscribes](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/async.dart#L117) whenever the stream changes. The only value that `Query` is adding currently over using `StreamBuilder` directly is that it prevents re-subscribing whenever the parent widget rebuilds. Since `QueryRequest` doesn't currently override "==", if the `QueryRequest` is created within the build method of the parent widget, it will have a new identity on every build and will cause `StreamBuilder` to re-subscribe.

By simply overriding "==" in `QueryRequest` (either directly or by implementing `built_value`) we should be able to just use `StreamBuilder` directly and remove the `Query` Widget altogether.

This should reduce the API footprint and make it more transparent to the user how the library works.

**Comment by iscriptology** [comment]
I think it conceptually wrong to develop a flutter library with `make it more transparent to the user how the library works.` in mind.

IMO (almost)nobody want to know how things work, people (and software!) want abstractions that work.

**Comment by smkhalsa** [comment]
Maybe I didn't express my primary point clearly: I don't believe the query
widget actually provides a useful abstraction over using StreamBuilder
directly and it adds bloat to the API.

**Comment by smkhalsa** [comment]
Here's a comparison of how you'd use the `Query` widget vs the native `StreamBuilder` widget.

With `Query`

```dart
Widget build(BuildContext context) {
  return Query(
    client: client,
    queryRequest: MyQuery(),
    builder: (BuildContext context, QueryResponse<$MyQuery> response) {
      final data = response?.data;
      /// do something with data
    });
}
```

With `StreamBuilder`

```dart
Widget build(BuildContext context) {
  return StreamBuilder(
    stream: client.responseStream(MyQuery()),
    builder: (BuildContext context, AsyncSnapshot<QueryResponse<$MyQuery>> snapshot) {
      final data = snapshot.data?.data;
      /// do something with data
    },
  );
}
```

**Comment by iscriptology** [comment]
`AsyncSnapshot<QueryResponse<$MyQuery>> snapshot` is a really not pleasant line to write.
also if you want to implement polling, caching, and more features a dedicated widget could be the place to go.

**Comment by smkhalsa** [comment]
> AsyncSnapshot<QueryResponse<$MyQuery>> snapshot, final data = snapshot.data?.data;

This doesn't seem compelling enough to keep a redundant abstraction.

> also if you want to implement polling, caching, and more features a dedicated widget could be the place to go.

These features would be implemented in the client core, not the widget. If you want to open a separate issue to discuss any of these features, feel free to do so.

**Comment by klavs** [comment]
> I think it conceptually wrong to develop a flutter library with `make it more transparent to the user how the library works.` in mind.
>
> IMO (almost)nobody want to know how things work, people (and software!) want abstractions that work.

@iscriptology, look at it this way - there is exactly one contributor to this client, @smkhalsa. Conceptually, the decision to drop any Flutter-specific code is a prioritization move. For Flutter-specific code to work well, the core client needs to work well. Additional Flutter support can be added at any later time. Meanwhile, anyone, including you, is free to built their own Flutter layer atop of Ferry.

> also if you want to implement polling, caching, and more features a dedicated widget could be the place to go.

If you are familiar with the history of `partialRefetch` in Apollo, for example, you'll know it's not a good idea to add anything but the minimum to the framework wrapper.
